// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: lead.proto

package leadexchangev1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LeadStatus — статус лида.
type LeadStatus int32

const (
	LeadStatus_LEAD_STATUS_UNSPECIFIED LeadStatus = 0
	LeadStatus_LEAD_STATUS_NEW         LeadStatus = 1
	LeadStatus_LEAD_STATUS_PUBLISHED   LeadStatus = 2
	LeadStatus_LEAD_STATUS_PURCHASED   LeadStatus = 3
	LeadStatus_LEAD_STATUS_DELETED     LeadStatus = 4
)

// Enum value maps for LeadStatus.
var (
	LeadStatus_name = map[int32]string{
		0: "LEAD_STATUS_UNSPECIFIED",
		1: "LEAD_STATUS_NEW",
		2: "LEAD_STATUS_PUBLISHED",
		3: "LEAD_STATUS_PURCHASED",
		4: "LEAD_STATUS_DELETED",
	}
	LeadStatus_value = map[string]int32{
		"LEAD_STATUS_UNSPECIFIED": 0,
		"LEAD_STATUS_NEW":         1,
		"LEAD_STATUS_PUBLISHED":   2,
		"LEAD_STATUS_PURCHASED":   3,
		"LEAD_STATUS_DELETED":     4,
	}
)

func (x LeadStatus) Enum() *LeadStatus {
	p := new(LeadStatus)
	*p = x
	return p
}

func (x LeadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lead_proto_enumTypes[0].Descriptor()
}

func (LeadStatus) Type() protoreflect.EnumType {
	return &file_lead_proto_enumTypes[0]
}

func (x LeadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeadStatus.Descriptor instead.
func (LeadStatus) EnumDescriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{0}
}

// Lead — сущность лида.
type Lead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Requirement   []byte                 `protobuf:"bytes,4,opt,name=requirement,proto3" json:"requirement,omitempty"`
	ContactName   string                 `protobuf:"bytes,5,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactPhone  string                 `protobuf:"bytes,6,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,7,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Status        LeadStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=leadexchange.v1.LeadStatus" json:"status,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,9,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	CreatedUserId string                 `protobuf:"bytes,10,opt,name=created_user_id,json=createdUserId,proto3" json:"created_user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	City          *string                `protobuf:"bytes,13,opt,name=city,proto3,oneof" json:"city,omitempty"`
	PropertyType  PropertyType           `protobuf:"varint,14,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType" json:"property_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lead) Reset() {
	*x = Lead{}
	mi := &file_lead_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lead) ProtoMessage() {}

func (x *Lead) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lead.ProtoReflect.Descriptor instead.
func (*Lead) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{0}
}

func (x *Lead) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *Lead) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lead) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Lead) GetRequirement() []byte {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *Lead) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Lead) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *Lead) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *Lead) GetStatus() LeadStatus {
	if x != nil {
		return x.Status
	}
	return LeadStatus_LEAD_STATUS_UNSPECIFIED
}

func (x *Lead) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Lead) GetCreatedUserId() string {
	if x != nil {
		return x.CreatedUserId
	}
	return ""
}

func (x *Lead) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Lead) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Lead) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *Lead) GetPropertyType() PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

type CreateLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Requirement   []byte                 `protobuf:"bytes,3,opt,name=requirement,proto3" json:"requirement,omitempty"`
	ContactName   string                 `protobuf:"bytes,4,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactPhone  string                 `protobuf:"bytes,5,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,6,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	City          *string                `protobuf:"bytes,7,opt,name=city,proto3,oneof" json:"city,omitempty"`
	PropertyType  PropertyType           `protobuf:"varint,8,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType" json:"property_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeadRequest) Reset() {
	*x = CreateLeadRequest{}
	mi := &file_lead_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeadRequest) ProtoMessage() {}

func (x *CreateLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeadRequest.ProtoReflect.Descriptor instead.
func (*CreateLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLeadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLeadRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLeadRequest) GetRequirement() []byte {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *CreateLeadRequest) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *CreateLeadRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *CreateLeadRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *CreateLeadRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *CreateLeadRequest) GetPropertyType() PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

type GetLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadRequest) Reset() {
	*x = GetLeadRequest{}
	mi := &file_lead_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadRequest) ProtoMessage() {}

func (x *GetLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadRequest.ProtoReflect.Descriptor instead.
func (*GetLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeadRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

type ListLeadsRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Filter         *ListLeadsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize       *int32                   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken      *string                  `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	OrderBy        *string                  `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	OrderDirection *string                  `protobuf:"bytes,5,opt,name=order_direction,json=orderDirection,proto3,oneof" json:"order_direction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListLeadsRequest) Reset() {
	*x = ListLeadsRequest{}
	mi := &file_lead_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsRequest) ProtoMessage() {}

func (x *ListLeadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsRequest.ProtoReflect.Descriptor instead.
func (*ListLeadsRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{3}
}

func (x *ListLeadsRequest) GetFilter() *ListLeadsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListLeadsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListLeadsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListLeadsRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListLeadsRequest) GetOrderDirection() string {
	if x != nil && x.OrderDirection != nil {
		return *x.OrderDirection
	}
	return ""
}

type ReindexLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexLeadRequest) Reset() {
	*x = ReindexLeadRequest{}
	mi := &file_lead_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexLeadRequest) ProtoMessage() {}

func (x *ReindexLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexLeadRequest.ProtoReflect.Descriptor instead.
func (*ReindexLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{4}
}

func (x *ReindexLeadRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

type ReindexLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexLeadResponse) Reset() {
	*x = ReindexLeadResponse{}
	mi := &file_lead_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexLeadResponse) ProtoMessage() {}

func (x *ReindexLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexLeadResponse.ProtoReflect.Descriptor instead.
func (*ReindexLeadResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{5}
}

func (x *ReindexLeadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReindexLeadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListLeadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leads         []*Lead                `protobuf:"bytes,1,rep,name=leads,proto3" json:"leads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsResponse) Reset() {
	*x = ListLeadsResponse{}
	mi := &file_lead_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsResponse) ProtoMessage() {}

func (x *ListLeadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsResponse.ProtoReflect.Descriptor instead.
func (*ListLeadsResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{6}
}

func (x *ListLeadsResponse) GetLeads() []*Lead {
	if x != nil {
		return x.Leads
	}
	return nil
}

type UpdateLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Requirement   []byte                 `protobuf:"bytes,4,opt,name=requirement,proto3,oneof" json:"requirement,omitempty"`
	Status        *LeadStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=leadexchange.v1.LeadStatus,oneof" json:"status,omitempty"`
	OwnerUserId   *string                `protobuf:"bytes,6,opt,name=owner_user_id,json=ownerUserId,proto3,oneof" json:"owner_user_id,omitempty"`
	City          *string                `protobuf:"bytes,7,opt,name=city,proto3,oneof" json:"city,omitempty"`
	PropertyType  *PropertyType          `protobuf:"varint,8,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType,oneof" json:"property_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeadRequest) Reset() {
	*x = UpdateLeadRequest{}
	mi := &file_lead_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeadRequest) ProtoMessage() {}

func (x *UpdateLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeadRequest.ProtoReflect.Descriptor instead.
func (*UpdateLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLeadRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *UpdateLeadRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateLeadRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateLeadRequest) GetRequirement() []byte {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *UpdateLeadRequest) GetStatus() LeadStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return LeadStatus_LEAD_STATUS_UNSPECIFIED
}

func (x *UpdateLeadRequest) GetOwnerUserId() string {
	if x != nil && x.OwnerUserId != nil {
		return *x.OwnerUserId
	}
	return ""
}

func (x *UpdateLeadRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateLeadRequest) GetPropertyType() PropertyType {
	if x != nil && x.PropertyType != nil {
		return *x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

type LeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lead          *Lead                  `protobuf:"bytes,1,opt,name=lead,proto3" json:"lead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadResponse) Reset() {
	*x = LeadResponse{}
	mi := &file_lead_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadResponse) ProtoMessage() {}

func (x *LeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadResponse.ProtoReflect.Descriptor instead.
func (*LeadResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{8}
}

func (x *LeadResponse) GetLead() *Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

type GetClarificationQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClarificationQuestionsRequest) Reset() {
	*x = GetClarificationQuestionsRequest{}
	mi := &file_lead_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClarificationQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClarificationQuestionsRequest) ProtoMessage() {}

func (x *GetClarificationQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClarificationQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetClarificationQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{9}
}

func (x *GetClarificationQuestionsRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

type ClarificationQuestion struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Field            string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Question         string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	QuestionType     string                 `protobuf:"bytes,3,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	SuggestedOptions []string               `protobuf:"bytes,4,rep,name=suggested_options,json=suggestedOptions,proto3" json:"suggested_options,omitempty"`
	Importance       string                 `protobuf:"bytes,5,opt,name=importance,proto3" json:"importance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClarificationQuestion) Reset() {
	*x = ClarificationQuestion{}
	mi := &file_lead_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClarificationQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClarificationQuestion) ProtoMessage() {}

func (x *ClarificationQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClarificationQuestion.ProtoReflect.Descriptor instead.
func (*ClarificationQuestion) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{10}
}

func (x *ClarificationQuestion) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ClarificationQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *ClarificationQuestion) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *ClarificationQuestion) GetSuggestedOptions() []string {
	if x != nil {
		return x.SuggestedOptions
	}
	return nil
}

func (x *ClarificationQuestion) GetImportance() string {
	if x != nil {
		return x.Importance
	}
	return ""
}

type GetClarificationQuestionsResponse struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	NeedsClarification bool                     `protobuf:"varint,1,opt,name=needs_clarification,json=needsClarification,proto3" json:"needs_clarification,omitempty"`
	Questions          []*ClarificationQuestion `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	Priority           string                   `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	MissingFields      []string                 `protobuf:"bytes,4,rep,name=missing_fields,json=missingFields,proto3" json:"missing_fields,omitempty"`
	LeadQualityScore   float64                  `protobuf:"fixed64,5,opt,name=lead_quality_score,json=leadQualityScore,proto3" json:"lead_quality_score,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetClarificationQuestionsResponse) Reset() {
	*x = GetClarificationQuestionsResponse{}
	mi := &file_lead_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClarificationQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClarificationQuestionsResponse) ProtoMessage() {}

func (x *GetClarificationQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClarificationQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetClarificationQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{11}
}

func (x *GetClarificationQuestionsResponse) GetNeedsClarification() bool {
	if x != nil {
		return x.NeedsClarification
	}
	return false
}

func (x *GetClarificationQuestionsResponse) GetQuestions() []*ClarificationQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GetClarificationQuestionsResponse) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *GetClarificationQuestionsResponse) GetMissingFields() []string {
	if x != nil {
		return x.MissingFields
	}
	return nil
}

func (x *GetClarificationQuestionsResponse) GetLeadQualityScore() float64 {
	if x != nil {
		return x.LeadQualityScore
	}
	return 0
}

type ClarificationAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClarificationAnswer) Reset() {
	*x = ClarificationAnswer{}
	mi := &file_lead_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClarificationAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClarificationAnswer) ProtoMessage() {}

func (x *ClarificationAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClarificationAnswer.ProtoReflect.Descriptor instead.
func (*ClarificationAnswer) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{12}
}

func (x *ClarificationAnswer) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ClarificationAnswer) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ApplyClarificationAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Answers       []*ClarificationAnswer `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyClarificationAnswersRequest) Reset() {
	*x = ApplyClarificationAnswersRequest{}
	mi := &file_lead_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyClarificationAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyClarificationAnswersRequest) ProtoMessage() {}

func (x *ApplyClarificationAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyClarificationAnswersRequest.ProtoReflect.Descriptor instead.
func (*ApplyClarificationAnswersRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyClarificationAnswersRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *ApplyClarificationAnswersRequest) GetAnswers() []*ClarificationAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type ApplyClarificationAnswersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewRequirement []byte                 `protobuf:"bytes,2,opt,name=new_requirement,json=newRequirement,proto3" json:"new_requirement,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyClarificationAnswersResponse) Reset() {
	*x = ApplyClarificationAnswersResponse{}
	mi := &file_lead_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyClarificationAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyClarificationAnswersResponse) ProtoMessage() {}

func (x *ApplyClarificationAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyClarificationAnswersResponse.ProtoReflect.Descriptor instead.
func (*ApplyClarificationAnswersResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{14}
}

func (x *ApplyClarificationAnswersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyClarificationAnswersResponse) GetNewRequirement() []byte {
	if x != nil {
		return x.NewRequirement
	}
	return nil
}

func (x *ApplyClarificationAnswersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MatchWeights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	District      float64                `protobuf:"fixed64,2,opt,name=district,proto3" json:"district,omitempty"`
	Rooms         float64                `protobuf:"fixed64,3,opt,name=rooms,proto3" json:"rooms,omitempty"`
	Area          float64                `protobuf:"fixed64,4,opt,name=area,proto3" json:"area,omitempty"`
	Semantic      float64                `protobuf:"fixed64,5,opt,name=semantic,proto3" json:"semantic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchWeights) Reset() {
	*x = MatchWeights{}
	mi := &file_lead_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchWeights) ProtoMessage() {}

func (x *MatchWeights) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchWeights.ProtoReflect.Descriptor instead.
func (*MatchWeights) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{15}
}

func (x *MatchWeights) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MatchWeights) GetDistrict() float64 {
	if x != nil {
		return x.District
	}
	return 0
}

func (x *MatchWeights) GetRooms() float64 {
	if x != nil {
		return x.Rooms
	}
	return 0
}

func (x *MatchWeights) GetArea() float64 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *MatchWeights) GetSemantic() float64 {
	if x != nil {
		return x.Semantic
	}
	return 0
}

type ExtractedCriteria struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TargetPrice        *int64                 `protobuf:"varint,1,opt,name=target_price,json=targetPrice,proto3,oneof" json:"target_price,omitempty"`
	TargetDistrict     *string                `protobuf:"bytes,2,opt,name=target_district,json=targetDistrict,proto3,oneof" json:"target_district,omitempty"`
	TargetRooms        *int32                 `protobuf:"varint,3,opt,name=target_rooms,json=targetRooms,proto3,oneof" json:"target_rooms,omitempty"`
	TargetArea         *float64               `protobuf:"fixed64,4,opt,name=target_area,json=targetArea,proto3,oneof" json:"target_area,omitempty"`
	PreferredDistricts []string               `protobuf:"bytes,5,rep,name=preferred_districts,json=preferredDistricts,proto3" json:"preferred_districts,omitempty"`
	MustHaveFeatures   []string               `protobuf:"bytes,6,rep,name=must_have_features,json=mustHaveFeatures,proto3" json:"must_have_features,omitempty"`
	NiceToHaveFeatures []string               `protobuf:"bytes,7,rep,name=nice_to_have_features,json=niceToHaveFeatures,proto3" json:"nice_to_have_features,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExtractedCriteria) Reset() {
	*x = ExtractedCriteria{}
	mi := &file_lead_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractedCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractedCriteria) ProtoMessage() {}

func (x *ExtractedCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractedCriteria.ProtoReflect.Descriptor instead.
func (*ExtractedCriteria) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{16}
}

func (x *ExtractedCriteria) GetTargetPrice() int64 {
	if x != nil && x.TargetPrice != nil {
		return *x.TargetPrice
	}
	return 0
}

func (x *ExtractedCriteria) GetTargetDistrict() string {
	if x != nil && x.TargetDistrict != nil {
		return *x.TargetDistrict
	}
	return ""
}

func (x *ExtractedCriteria) GetTargetRooms() int32 {
	if x != nil && x.TargetRooms != nil {
		return *x.TargetRooms
	}
	return 0
}

func (x *ExtractedCriteria) GetTargetArea() float64 {
	if x != nil && x.TargetArea != nil {
		return *x.TargetArea
	}
	return 0
}

func (x *ExtractedCriteria) GetPreferredDistricts() []string {
	if x != nil {
		return x.PreferredDistricts
	}
	return nil
}

func (x *ExtractedCriteria) GetMustHaveFeatures() []string {
	if x != nil {
		return x.MustHaveFeatures
	}
	return nil
}

func (x *ExtractedCriteria) GetNiceToHaveFeatures() []string {
	if x != nil {
		return x.NiceToHaveFeatures
	}
	return nil
}

type AnalyzeLeadIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeLeadIntentRequest) Reset() {
	*x = AnalyzeLeadIntentRequest{}
	mi := &file_lead_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeLeadIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeLeadIntentRequest) ProtoMessage() {}

func (x *AnalyzeLeadIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeLeadIntentRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeLeadIntentRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{17}
}

func (x *AnalyzeLeadIntentRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

type AnalyzeLeadIntentResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecommendedWeights *MatchWeights          `protobuf:"bytes,1,opt,name=recommended_weights,json=recommendedWeights,proto3" json:"recommended_weights,omitempty"`
	ExtractedCriteria  *ExtractedCriteria     `protobuf:"bytes,2,opt,name=extracted_criteria,json=extractedCriteria,proto3" json:"extracted_criteria,omitempty"`
	LeadType           string                 `protobuf:"bytes,3,opt,name=lead_type,json=leadType,proto3" json:"lead_type,omitempty"`
	Confidence         float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Explanation        string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	UsedLlm            bool                   `protobuf:"varint,6,opt,name=used_llm,json=usedLlm,proto3" json:"used_llm,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AnalyzeLeadIntentResponse) Reset() {
	*x = AnalyzeLeadIntentResponse{}
	mi := &file_lead_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeLeadIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeLeadIntentResponse) ProtoMessage() {}

func (x *AnalyzeLeadIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeLeadIntentResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeLeadIntentResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{18}
}

func (x *AnalyzeLeadIntentResponse) GetRecommendedWeights() *MatchWeights {
	if x != nil {
		return x.RecommendedWeights
	}
	return nil
}

func (x *AnalyzeLeadIntentResponse) GetExtractedCriteria() *ExtractedCriteria {
	if x != nil {
		return x.ExtractedCriteria
	}
	return nil
}

func (x *AnalyzeLeadIntentResponse) GetLeadType() string {
	if x != nil {
		return x.LeadType
	}
	return ""
}

func (x *AnalyzeLeadIntentResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeLeadIntentResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *AnalyzeLeadIntentResponse) GetUsedLlm() bool {
	if x != nil {
		return x.UsedLlm
	}
	return false
}

type ListLeadsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *LeadStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=leadexchange.v1.LeadStatus,oneof" json:"status,omitempty"`
	OwnerUserId   *string                `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3,oneof" json:"owner_user_id,omitempty"`
	CreatedUserId *string                `protobuf:"bytes,3,opt,name=created_user_id,json=createdUserId,proto3,oneof" json:"created_user_id,omitempty"`
	City          *string                `protobuf:"bytes,4,opt,name=city,proto3,oneof" json:"city,omitempty"`
	PropertyType  *PropertyType          `protobuf:"varint,5,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType,oneof" json:"property_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsRequest_Filter) Reset() {
	*x = ListLeadsRequest_Filter{}
	mi := &file_lead_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsRequest_Filter) ProtoMessage() {}

func (x *ListLeadsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListLeadsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListLeadsRequest_Filter) GetStatus() LeadStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return LeadStatus_LEAD_STATUS_UNSPECIFIED
}

func (x *ListLeadsRequest_Filter) GetOwnerUserId() string {
	if x != nil && x.OwnerUserId != nil {
		return *x.OwnerUserId
	}
	return ""
}

func (x *ListLeadsRequest_Filter) GetCreatedUserId() string {
	if x != nil && x.CreatedUserId != nil {
		return *x.CreatedUserId
	}
	return ""
}

func (x *ListLeadsRequest_Filter) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *ListLeadsRequest_Filter) GetPropertyType() PropertyType {
	if x != nil && x.PropertyType != nil {
		return *x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

var File_lead_proto protoreflect.FileDescriptor

const file_lead_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"lead.proto\x12\x0fleadexchange.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x0eproperty.proto\"\xd9\x04\n" +
	"\x04Lead\x12\x17\n" +
	"\alead_id\x18\x01 \x01(\tR\x06leadId\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12 \n" +
	"\vrequirement\x18\x04 \x01(\fR\vrequirement\x12*\n" +
	"\fcontact_name\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\vcontactName\x12?\n" +
	"\rcontact_phone\x18\x06 \x01(\tB\x1a\xfaB\x17r\x152\x13^\\+?[0-9\\s()-]{7,}$R\fcontactPhone\x12/\n" +
	"\rcontact_email\x18\a \x01(\tB\n" +
	"\xfaB\ar\x05\xd0\x01\x01`\x01R\fcontactEmail\x123\n" +
	"\x06status\x18\b \x01(\x0e2\x1b.leadexchange.v1.LeadStatusR\x06status\x12,\n" +
	"\rowner_user_id\x18\t \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\vownerUserId\x120\n" +
	"\x0fcreated_user_id\x18\n" +
	" \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\rcreatedUserId\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12\x17\n" +
	"\x04city\x18\r \x01(\tH\x00R\x04city\x88\x01\x01\x12B\n" +
	"\rproperty_type\x18\x0e \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeR\fpropertyTypeB\a\n" +
	"\x05_city\"\xfa\x02\n" +
	"\x11CreateLeadRequest\x12\x1d\n" +
	"\x05title\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12 \n" +
	"\vrequirement\x18\x03 \x01(\fR\vrequirement\x12*\n" +
	"\fcontact_name\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\vcontactName\x12?\n" +
	"\rcontact_phone\x18\x05 \x01(\tB\x1a\xfaB\x17r\x152\x13^\\+?[0-9\\s()-]{7,}$R\fcontactPhone\x12/\n" +
	"\rcontact_email\x18\x06 \x01(\tB\n" +
	"\xfaB\ar\x05\xd0\x01\x01`\x01R\fcontactEmail\x12\x17\n" +
	"\x04city\x18\a \x01(\tH\x00R\x04city\x88\x01\x01\x12B\n" +
	"\rproperty_type\x18\b \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeR\fpropertyTypeB\a\n" +
	"\x05_city\"3\n" +
	"\x0eGetLeadRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\"\xef\x04\n" +
	"\x10ListLeadsRequest\x12@\n" +
	"\x06filter\x18\x01 \x01(\v2(.leadexchange.v1.ListLeadsRequest.FilterR\x06filter\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tH\x01R\tpageToken\x88\x01\x01\x12\x1e\n" +
	"\border_by\x18\x04 \x01(\tH\x02R\aorderBy\x88\x01\x01\x12,\n" +
	"\x0forder_direction\x18\x05 \x01(\tH\x03R\x0eorderDirection\x88\x01\x01\x1a\xc6\x02\n" +
	"\x06Filter\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.leadexchange.v1.LeadStatusH\x00R\x06status\x88\x01\x01\x12'\n" +
	"\rowner_user_id\x18\x02 \x01(\tH\x01R\vownerUserId\x88\x01\x01\x12+\n" +
	"\x0fcreated_user_id\x18\x03 \x01(\tH\x02R\rcreatedUserId\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x04 \x01(\tH\x03R\x04city\x88\x01\x01\x12G\n" +
	"\rproperty_type\x18\x05 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeH\x04R\fpropertyType\x88\x01\x01B\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_owner_user_idB\x12\n" +
	"\x10_created_user_idB\a\n" +
	"\x05_cityB\x10\n" +
	"\x0e_property_typeB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\v\n" +
	"\t_order_byB\x12\n" +
	"\x10_order_direction\"7\n" +
	"\x12ReindexLeadRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\"I\n" +
	"\x13ReindexLeadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\x11ListLeadsResponse\x12+\n" +
	"\x05leads\x18\x01 \x03(\v2\x15.leadexchange.v1.LeadR\x05leads\"\xc6\x03\n" +
	"\x11UpdateLeadRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12%\n" +
	"\vrequirement\x18\x04 \x01(\fH\x02R\vrequirement\x88\x01\x01\x128\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.leadexchange.v1.LeadStatusH\x03R\x06status\x88\x01\x01\x12'\n" +
	"\rowner_user_id\x18\x06 \x01(\tH\x04R\vownerUserId\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\a \x01(\tH\x05R\x04city\x88\x01\x01\x12G\n" +
	"\rproperty_type\x18\b \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeH\x06R\fpropertyType\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_requirementB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_owner_user_idB\a\n" +
	"\x05_cityB\x10\n" +
	"\x0e_property_type\"9\n" +
	"\fLeadResponse\x12)\n" +
	"\x04lead\x18\x01 \x01(\v2\x15.leadexchange.v1.LeadR\x04lead\"E\n" +
	" GetClarificationQuestionsRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\"\xbb\x01\n" +
	"\x15ClarificationQuestion\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12#\n" +
	"\rquestion_type\x18\x03 \x01(\tR\fquestionType\x12+\n" +
	"\x11suggested_options\x18\x04 \x03(\tR\x10suggestedOptions\x12\x1e\n" +
	"\n" +
	"importance\x18\x05 \x01(\tR\n" +
	"importance\"\x8b\x02\n" +
	"!GetClarificationQuestionsResponse\x12/\n" +
	"\x13needs_clarification\x18\x01 \x01(\bR\x12needsClarification\x12D\n" +
	"\tquestions\x18\x02 \x03(\v2&.leadexchange.v1.ClarificationQuestionR\tquestions\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12%\n" +
	"\x0emissing_fields\x18\x04 \x03(\tR\rmissingFields\x12,\n" +
	"\x12lead_quality_score\x18\x05 \x01(\x01R\x10leadQualityScore\"A\n" +
	"\x13ClarificationAnswer\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x85\x01\n" +
	" ApplyClarificationAnswersRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\x12>\n" +
	"\aanswers\x18\x02 \x03(\v2$.leadexchange.v1.ClarificationAnswerR\aanswers\"\x80\x01\n" +
	"!ApplyClarificationAnswersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fnew_requirement\x18\x02 \x01(\fR\x0enewRequirement\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x86\x01\n" +
	"\fMatchWeights\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bdistrict\x18\x02 \x01(\x01R\bdistrict\x12\x14\n" +
	"\x05rooms\x18\x03 \x01(\x01R\x05rooms\x12\x12\n" +
	"\x04area\x18\x04 \x01(\x01R\x04area\x12\x1a\n" +
	"\bsemantic\x18\x05 \x01(\x01R\bsemantic\"\x8f\x03\n" +
	"\x11ExtractedCriteria\x12&\n" +
	"\ftarget_price\x18\x01 \x01(\x03H\x00R\vtargetPrice\x88\x01\x01\x12,\n" +
	"\x0ftarget_district\x18\x02 \x01(\tH\x01R\x0etargetDistrict\x88\x01\x01\x12&\n" +
	"\ftarget_rooms\x18\x03 \x01(\x05H\x02R\vtargetRooms\x88\x01\x01\x12$\n" +
	"\vtarget_area\x18\x04 \x01(\x01H\x03R\n" +
	"targetArea\x88\x01\x01\x12/\n" +
	"\x13preferred_districts\x18\x05 \x03(\tR\x12preferredDistricts\x12,\n" +
	"\x12must_have_features\x18\x06 \x03(\tR\x10mustHaveFeatures\x121\n" +
	"\x15nice_to_have_features\x18\a \x03(\tR\x12niceToHaveFeaturesB\x0f\n" +
	"\r_target_priceB\x12\n" +
	"\x10_target_districtB\x0f\n" +
	"\r_target_roomsB\x0e\n" +
	"\f_target_area\"=\n" +
	"\x18AnalyzeLeadIntentRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\"\xb8\x02\n" +
	"\x19AnalyzeLeadIntentResponse\x12N\n" +
	"\x13recommended_weights\x18\x01 \x01(\v2\x1d.leadexchange.v1.MatchWeightsR\x12recommendedWeights\x12Q\n" +
	"\x12extracted_criteria\x18\x02 \x01(\v2\".leadexchange.v1.ExtractedCriteriaR\x11extractedCriteria\x12\x1b\n" +
	"\tlead_type\x18\x03 \x01(\tR\bleadType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x12\x19\n" +
	"\bused_llm\x18\x06 \x01(\bR\ausedLlm*\x8d\x01\n" +
	"\n" +
	"LeadStatus\x12\x1b\n" +
	"\x17LEAD_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLEAD_STATUS_NEW\x10\x01\x12\x19\n" +
	"\x15LEAD_STATUS_PUBLISHED\x10\x02\x12\x19\n" +
	"\x15LEAD_STATUS_PURCHASED\x10\x03\x12\x17\n" +
	"\x13LEAD_STATUS_DELETED\x10\x042\xac\b\n" +
	"\vLeadService\x12e\n" +
	"\n" +
	"CreateLead\x12\".leadexchange.v1.CreateLeadRequest\x1a\x1d.leadexchange.v1.LeadResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/leads\x12f\n" +
	"\aGetLead\x12\x1f.leadexchange.v1.GetLeadRequest\x1a\x1d.leadexchange.v1.LeadResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/leads/{lead_id}\x12e\n" +
	"\tListLeads\x12!.leadexchange.v1.ListLeadsRequest\x1a\".leadexchange.v1.ListLeadsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/leads\x12o\n" +
	"\n" +
	"UpdateLead\x12\".leadexchange.v1.UpdateLeadRequest\x1a\x1d.leadexchange.v1.LeadResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*2\x13/v1/leads/{lead_id}\x12\x80\x01\n" +
	"\vReindexLead\x12#.leadexchange.v1.ReindexLeadRequest\x1a$.leadexchange.v1.ReindexLeadResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/leads/{lead_id}/reindex\x12\xad\x01\n" +
	"\x19GetClarificationQuestions\x121.leadexchange.v1.GetClarificationQuestionsRequest\x1a2.leadexchange.v1.GetClarificationQuestionsResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/leads/{lead_id}/clarification\x12\xb0\x01\n" +
	"\x19ApplyClarificationAnswers\x121.leadexchange.v1.ApplyClarificationAnswersRequest\x1a2.leadexchange.v1.ApplyClarificationAnswersResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/leads/{lead_id}/clarification\x12\x8f\x01\n" +
	"\x11AnalyzeLeadIntent\x12).leadexchange.v1.AnalyzeLeadIntentRequest\x1a*.leadexchange.v1.AnalyzeLeadIntentResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/leads/{lead_id}/analyzeB4Z2leadexchange/gen/go/leadexchange/v1;leadexchangev1b\x06proto3"

var (
	file_lead_proto_rawDescOnce sync.Once
	file_lead_proto_rawDescData []byte
)

func file_lead_proto_rawDescGZIP() []byte {
	file_lead_proto_rawDescOnce.Do(func() {
		file_lead_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lead_proto_rawDesc), len(file_lead_proto_rawDesc)))
	})
	return file_lead_proto_rawDescData
}

var file_lead_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lead_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_lead_proto_goTypes = []any{
	(LeadStatus)(0),                           // 0: leadexchange.v1.LeadStatus
	(*Lead)(nil),                              // 1: leadexchange.v1.Lead
	(*CreateLeadRequest)(nil),                 // 2: leadexchange.v1.CreateLeadRequest
	(*GetLeadRequest)(nil),                    // 3: leadexchange.v1.GetLeadRequest
	(*ListLeadsRequest)(nil),                  // 4: leadexchange.v1.ListLeadsRequest
	(*ReindexLeadRequest)(nil),                // 5: leadexchange.v1.ReindexLeadRequest
	(*ReindexLeadResponse)(nil),               // 6: leadexchange.v1.ReindexLeadResponse
	(*ListLeadsResponse)(nil),                 // 7: leadexchange.v1.ListLeadsResponse
	(*UpdateLeadRequest)(nil),                 // 8: leadexchange.v1.UpdateLeadRequest
	(*LeadResponse)(nil),                      // 9: leadexchange.v1.LeadResponse
	(*GetClarificationQuestionsRequest)(nil),  // 10: leadexchange.v1.GetClarificationQuestionsRequest
	(*ClarificationQuestion)(nil),             // 11: leadexchange.v1.ClarificationQuestion
	(*GetClarificationQuestionsResponse)(nil), // 12: leadexchange.v1.GetClarificationQuestionsResponse
	(*ClarificationAnswer)(nil),               // 13: leadexchange.v1.ClarificationAnswer
	(*ApplyClarificationAnswersRequest)(nil),  // 14: leadexchange.v1.ApplyClarificationAnswersRequest
	(*ApplyClarificationAnswersResponse)(nil), // 15: leadexchange.v1.ApplyClarificationAnswersResponse
	(*MatchWeights)(nil),                      // 16: leadexchange.v1.MatchWeights
	(*ExtractedCriteria)(nil),                 // 17: leadexchange.v1.ExtractedCriteria
	(*AnalyzeLeadIntentRequest)(nil),          // 18: leadexchange.v1.AnalyzeLeadIntentRequest
	(*AnalyzeLeadIntentResponse)(nil),         // 19: leadexchange.v1.AnalyzeLeadIntentResponse
	(*ListLeadsRequest_Filter)(nil),           // 20: leadexchange.v1.ListLeadsRequest.Filter
	(PropertyType)(0),                         // 21: leadexchange.v1.PropertyType
}
var file_lead_proto_depIdxs = []int32{
	0,  // 0: leadexchange.v1.Lead.status:type_name -> leadexchange.v1.LeadStatus
	21, // 1: leadexchange.v1.Lead.property_type:type_name -> leadexchange.v1.PropertyType
	21, // 2: leadexchange.v1.CreateLeadRequest.property_type:type_name -> leadexchange.v1.PropertyType
	20, // 3: leadexchange.v1.ListLeadsRequest.filter:type_name -> leadexchange.v1.ListLeadsRequest.Filter
	1,  // 4: leadexchange.v1.ListLeadsResponse.leads:type_name -> leadexchange.v1.Lead
	0,  // 5: leadexchange.v1.UpdateLeadRequest.status:type_name -> leadexchange.v1.LeadStatus
	21, // 6: leadexchange.v1.UpdateLeadRequest.property_type:type_name -> leadexchange.v1.PropertyType
	1,  // 7: leadexchange.v1.LeadResponse.lead:type_name -> leadexchange.v1.Lead
	11, // 8: leadexchange.v1.GetClarificationQuestionsResponse.questions:type_name -> leadexchange.v1.ClarificationQuestion
	13, // 9: leadexchange.v1.ApplyClarificationAnswersRequest.answers:type_name -> leadexchange.v1.ClarificationAnswer
	16, // 10: leadexchange.v1.AnalyzeLeadIntentResponse.recommended_weights:type_name -> leadexchange.v1.MatchWeights
	17, // 11: leadexchange.v1.AnalyzeLeadIntentResponse.extracted_criteria:type_name -> leadexchange.v1.ExtractedCriteria
	0,  // 12: leadexchange.v1.ListLeadsRequest.Filter.status:type_name -> leadexchange.v1.LeadStatus
	21, // 13: leadexchange.v1.ListLeadsRequest.Filter.property_type:type_name -> leadexchange.v1.PropertyType
	2,  // 14: leadexchange.v1.LeadService.CreateLead:input_type -> leadexchange.v1.CreateLeadRequest
	3,  // 15: leadexchange.v1.LeadService.GetLead:input_type -> leadexchange.v1.GetLeadRequest
	4,  // 16: leadexchange.v1.LeadService.ListLeads:input_type -> leadexchange.v1.ListLeadsRequest
	8,  // 17: leadexchange.v1.LeadService.UpdateLead:input_type -> leadexchange.v1.UpdateLeadRequest
	5,  // 18: leadexchange.v1.LeadService.ReindexLead:input_type -> leadexchange.v1.ReindexLeadRequest
	10, // 19: leadexchange.v1.LeadService.GetClarificationQuestions:input_type -> leadexchange.v1.GetClarificationQuestionsRequest
	14, // 20: leadexchange.v1.LeadService.ApplyClarificationAnswers:input_type -> leadexchange.v1.ApplyClarificationAnswersRequest
	18, // 21: leadexchange.v1.LeadService.AnalyzeLeadIntent:input_type -> leadexchange.v1.AnalyzeLeadIntentRequest
	9,  // 22: leadexchange.v1.LeadService.CreateLead:output_type -> leadexchange.v1.LeadResponse
	9,  // 23: leadexchange.v1.LeadService.GetLead:output_type -> leadexchange.v1.LeadResponse
	7,  // 24: leadexchange.v1.LeadService.ListLeads:output_type -> leadexchange.v1.ListLeadsResponse
	9,  // 25: leadexchange.v1.LeadService.UpdateLead:output_type -> leadexchange.v1.LeadResponse
	6,  // 26: leadexchange.v1.LeadService.ReindexLead:output_type -> leadexchange.v1.ReindexLeadResponse
	12, // 27: leadexchange.v1.LeadService.GetClarificationQuestions:output_type -> leadexchange.v1.GetClarificationQuestionsResponse
	15, // 28: leadexchange.v1.LeadService.ApplyClarificationAnswers:output_type -> leadexchange.v1.ApplyClarificationAnswersResponse
	19, // 29: leadexchange.v1.LeadService.AnalyzeLeadIntent:output_type -> leadexchange.v1.AnalyzeLeadIntentResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_lead_proto_init() }
func file_lead_proto_init() {
	if File_lead_proto != nil {
		return
	}
	file_property_proto_init()
	file_lead_proto_msgTypes[0].OneofWrappers = []any{}
	file_lead_proto_msgTypes[1].OneofWrappers = []any{}
	file_lead_proto_msgTypes[3].OneofWrappers = []any{}
	file_lead_proto_msgTypes[7].OneofWrappers = []any{}
	file_lead_proto_msgTypes[16].OneofWrappers = []any{}
	file_lead_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lead_proto_rawDesc), len(file_lead_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lead_proto_goTypes,
		DependencyIndexes: file_lead_proto_depIdxs,
		EnumInfos:         file_lead_proto_enumTypes,
		MessageInfos:      file_lead_proto_msgTypes,
	}.Build()
	File_lead_proto = out.File
	file_lead_proto_goTypes = nil
	file_lead_proto_depIdxs = nil
}
