// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: lead.proto

package leadexchangev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeadService_CreateLead_FullMethodName                = "/leadexchange.v1.LeadService/CreateLead"
	LeadService_GetLead_FullMethodName                   = "/leadexchange.v1.LeadService/GetLead"
	LeadService_ListLeads_FullMethodName                 = "/leadexchange.v1.LeadService/ListLeads"
	LeadService_UpdateLead_FullMethodName                = "/leadexchange.v1.LeadService/UpdateLead"
	LeadService_ReindexLead_FullMethodName               = "/leadexchange.v1.LeadService/ReindexLead"
	LeadService_GetClarificationQuestions_FullMethodName = "/leadexchange.v1.LeadService/GetClarificationQuestions"
	LeadService_ApplyClarificationAnswers_FullMethodName = "/leadexchange.v1.LeadService/ApplyClarificationAnswers"
	LeadService_AnalyzeLeadIntent_FullMethodName         = "/leadexchange.v1.LeadService/AnalyzeLeadIntent"
)

// LeadServiceClient is the client API for LeadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeadServiceClient interface {
	// Создать нового лида.
	CreateLead(ctx context.Context, in *CreateLeadRequest, opts ...grpc.CallOption) (*LeadResponse, error)
	// Получить информацию о конкретном лиде.
	GetLead(ctx context.Context, in *GetLeadRequest, opts ...grpc.CallOption) (*LeadResponse, error)
	// Получить список лидов по фильтру.
	ListLeads(ctx context.Context, in *ListLeadsRequest, opts ...grpc.CallOption) (*ListLeadsResponse, error)
	// Обновить лида.
	UpdateLead(ctx context.Context, in *UpdateLeadRequest, opts ...grpc.CallOption) (*LeadResponse, error)
	// Переиндексировать лида вручную.
	ReindexLead(ctx context.Context, in *ReindexLeadRequest, opts ...grpc.CallOption) (*ReindexLeadResponse, error)
	// Получить уточняющие вопросы для "короткого" лида.
	GetClarificationQuestions(ctx context.Context, in *GetClarificationQuestionsRequest, opts ...grpc.CallOption) (*GetClarificationQuestionsResponse, error)
	// Применить ответы на уточняющие вопросы.
	ApplyClarificationAnswers(ctx context.Context, in *ApplyClarificationAnswersRequest, opts ...grpc.CallOption) (*ApplyClarificationAnswersResponse, error)
	// Анализ намерений лида для определения оптимальных весов матчинга.
	AnalyzeLeadIntent(ctx context.Context, in *AnalyzeLeadIntentRequest, opts ...grpc.CallOption) (*AnalyzeLeadIntentResponse, error)
}

type leadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeadServiceClient(cc grpc.ClientConnInterface) LeadServiceClient {
	return &leadServiceClient{cc}
}

func (c *leadServiceClient) CreateLead(ctx context.Context, in *CreateLeadRequest, opts ...grpc.CallOption) (*LeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeadResponse)
	err := c.cc.Invoke(ctx, LeadService_CreateLead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leadServiceClient) GetLead(ctx context.Context, in *GetLeadRequest, opts ...grpc.CallOption) (*LeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeadResponse)
	err := c.cc.Invoke(ctx, LeadService_GetLead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leadServiceClient) ListLeads(ctx context.Context, in *ListLeadsRequest, opts ...grpc.CallOption) (*ListLeadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeadsResponse)
	err := c.cc.Invoke(ctx, LeadService_ListLeads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leadServiceClient) UpdateLead(ctx context.Context, in *UpdateLeadRequest, opts ...grpc.CallOption) (*LeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeadResponse)
	err := c.cc.Invoke(ctx, LeadService_UpdateLead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leadServiceClient) ReindexLead(ctx context.Context, in *ReindexLeadRequest, opts ...grpc.CallOption) (*ReindexLeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReindexLeadResponse)
	err := c.cc.Invoke(ctx, LeadService_ReindexLead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leadServiceClient) GetClarificationQuestions(ctx context.Context, in *GetClarificationQuestionsRequest, opts ...grpc.CallOption) (*GetClarificationQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClarificationQuestionsResponse)
	err := c.cc.Invoke(ctx, LeadService_GetClarificationQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leadServiceClient) ApplyClarificationAnswers(ctx context.Context, in *ApplyClarificationAnswersRequest, opts ...grpc.CallOption) (*ApplyClarificationAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyClarificationAnswersResponse)
	err := c.cc.Invoke(ctx, LeadService_ApplyClarificationAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leadServiceClient) AnalyzeLeadIntent(ctx context.Context, in *AnalyzeLeadIntentRequest, opts ...grpc.CallOption) (*AnalyzeLeadIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeLeadIntentResponse)
	err := c.cc.Invoke(ctx, LeadService_AnalyzeLeadIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeadServiceServer is the server API for LeadService service.
// All implementations must embed UnimplementedLeadServiceServer
// for forward compatibility.
type LeadServiceServer interface {
	// Создать нового лида.
	CreateLead(context.Context, *CreateLeadRequest) (*LeadResponse, error)
	// Получить информацию о конкретном лиде.
	GetLead(context.Context, *GetLeadRequest) (*LeadResponse, error)
	// Получить список лидов по фильтру.
	ListLeads(context.Context, *ListLeadsRequest) (*ListLeadsResponse, error)
	// Обновить лида.
	UpdateLead(context.Context, *UpdateLeadRequest) (*LeadResponse, error)
	// Переиндексировать лида вручную.
	ReindexLead(context.Context, *ReindexLeadRequest) (*ReindexLeadResponse, error)
	// Получить уточняющие вопросы для "короткого" лида.
	GetClarificationQuestions(context.Context, *GetClarificationQuestionsRequest) (*GetClarificationQuestionsResponse, error)
	// Применить ответы на уточняющие вопросы.
	ApplyClarificationAnswers(context.Context, *ApplyClarificationAnswersRequest) (*ApplyClarificationAnswersResponse, error)
	// Анализ намерений лида для определения оптимальных весов матчинга.
	AnalyzeLeadIntent(context.Context, *AnalyzeLeadIntentRequest) (*AnalyzeLeadIntentResponse, error)
	mustEmbedUnimplementedLeadServiceServer()
}

// UnimplementedLeadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeadServiceServer struct{}

func (UnimplementedLeadServiceServer) CreateLead(context.Context, *CreateLeadRequest) (*LeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLead not implemented")
}
func (UnimplementedLeadServiceServer) GetLead(context.Context, *GetLeadRequest) (*LeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLead not implemented")
}
func (UnimplementedLeadServiceServer) ListLeads(context.Context, *ListLeadsRequest) (*ListLeadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeads not implemented")
}
func (UnimplementedLeadServiceServer) UpdateLead(context.Context, *UpdateLeadRequest) (*LeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLead not implemented")
}
func (UnimplementedLeadServiceServer) ReindexLead(context.Context, *ReindexLeadRequest) (*ReindexLeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReindexLead not implemented")
}
func (UnimplementedLeadServiceServer) GetClarificationQuestions(context.Context, *GetClarificationQuestionsRequest) (*GetClarificationQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClarificationQuestions not implemented")
}
func (UnimplementedLeadServiceServer) ApplyClarificationAnswers(context.Context, *ApplyClarificationAnswersRequest) (*ApplyClarificationAnswersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyClarificationAnswers not implemented")
}
func (UnimplementedLeadServiceServer) AnalyzeLeadIntent(context.Context, *AnalyzeLeadIntentRequest) (*AnalyzeLeadIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeLeadIntent not implemented")
}
func (UnimplementedLeadServiceServer) mustEmbedUnimplementedLeadServiceServer() {}
func (UnimplementedLeadServiceServer) testEmbeddedByValue()                     {}

// UnsafeLeadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeadServiceServer will
// result in compilation errors.
type UnsafeLeadServiceServer interface {
	mustEmbedUnimplementedLeadServiceServer()
}

func RegisterLeadServiceServer(s grpc.ServiceRegistrar, srv LeadServiceServer) {
	// If the following call panics, it indicates UnimplementedLeadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeadService_ServiceDesc, srv)
}

func _LeadService_CreateLead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeadServiceServer).CreateLead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeadService_CreateLead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeadServiceServer).CreateLead(ctx, req.(*CreateLeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeadService_GetLead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeadServiceServer).GetLead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeadService_GetLead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeadServiceServer).GetLead(ctx, req.(*GetLeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeadService_ListLeads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLeadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeadServiceServer).ListLeads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeadService_ListLeads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeadServiceServer).ListLeads(ctx, req.(*ListLeadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeadService_UpdateLead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeadServiceServer).UpdateLead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeadService_UpdateLead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeadServiceServer).UpdateLead(ctx, req.(*UpdateLeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeadService_ReindexLead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReindexLeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeadServiceServer).ReindexLead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeadService_ReindexLead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeadServiceServer).ReindexLead(ctx, req.(*ReindexLeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeadService_GetClarificationQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClarificationQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeadServiceServer).GetClarificationQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeadService_GetClarificationQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeadServiceServer).GetClarificationQuestions(ctx, req.(*GetClarificationQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeadService_ApplyClarificationAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyClarificationAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeadServiceServer).ApplyClarificationAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeadService_ApplyClarificationAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeadServiceServer).ApplyClarificationAnswers(ctx, req.(*ApplyClarificationAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeadService_AnalyzeLeadIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeLeadIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeadServiceServer).AnalyzeLeadIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeadService_AnalyzeLeadIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeadServiceServer).AnalyzeLeadIntent(ctx, req.(*AnalyzeLeadIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeadService_ServiceDesc is the grpc.ServiceDesc for LeadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leadexchange.v1.LeadService",
	HandlerType: (*LeadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLead",
			Handler:    _LeadService_CreateLead_Handler,
		},
		{
			MethodName: "GetLead",
			Handler:    _LeadService_GetLead_Handler,
		},
		{
			MethodName: "ListLeads",
			Handler:    _LeadService_ListLeads_Handler,
		},
		{
			MethodName: "UpdateLead",
			Handler:    _LeadService_UpdateLead_Handler,
		},
		{
			MethodName: "ReindexLead",
			Handler:    _LeadService_ReindexLead_Handler,
		},
		{
			MethodName: "GetClarificationQuestions",
			Handler:    _LeadService_GetClarificationQuestions_Handler,
		},
		{
			MethodName: "ApplyClarificationAnswers",
			Handler:    _LeadService_ApplyClarificationAnswers_Handler,
		},
		{
			MethodName: "AnalyzeLeadIntent",
			Handler:    _LeadService_AnalyzeLeadIntent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lead.proto",
}
