// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: property.proto

package leadexchangev1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PropertyType — тип недвижимости.
type PropertyType int32

const (
	PropertyType_PROPERTY_TYPE_UNSPECIFIED PropertyType = 0
	PropertyType_PROPERTY_TYPE_APARTMENT   PropertyType = 1
	PropertyType_PROPERTY_TYPE_HOUSE       PropertyType = 2
	PropertyType_PROPERTY_TYPE_COMMERCIAL  PropertyType = 3
	PropertyType_PROPERTY_TYPE_LAND        PropertyType = 4
)

// Enum value maps for PropertyType.
var (
	PropertyType_name = map[int32]string{
		0: "PROPERTY_TYPE_UNSPECIFIED",
		1: "PROPERTY_TYPE_APARTMENT",
		2: "PROPERTY_TYPE_HOUSE",
		3: "PROPERTY_TYPE_COMMERCIAL",
		4: "PROPERTY_TYPE_LAND",
	}
	PropertyType_value = map[string]int32{
		"PROPERTY_TYPE_UNSPECIFIED": 0,
		"PROPERTY_TYPE_APARTMENT":   1,
		"PROPERTY_TYPE_HOUSE":       2,
		"PROPERTY_TYPE_COMMERCIAL":  3,
		"PROPERTY_TYPE_LAND":        4,
	}
)

func (x PropertyType) Enum() *PropertyType {
	p := new(PropertyType)
	*p = x
	return p
}

func (x PropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_property_proto_enumTypes[0].Descriptor()
}

func (PropertyType) Type() protoreflect.EnumType {
	return &file_property_proto_enumTypes[0]
}

func (x PropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyType.Descriptor instead.
func (PropertyType) EnumDescriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{0}
}

// PropertyStatus — статус объекта недвижимости.
type PropertyStatus int32

const (
	PropertyStatus_PROPERTY_STATUS_UNSPECIFIED PropertyStatus = 0
	PropertyStatus_PROPERTY_STATUS_NEW         PropertyStatus = 1
	PropertyStatus_PROPERTY_STATUS_PUBLISHED   PropertyStatus = 2
	PropertyStatus_PROPERTY_STATUS_SOLD        PropertyStatus = 3
	PropertyStatus_PROPERTY_STATUS_DELETED     PropertyStatus = 4
)

// Enum value maps for PropertyStatus.
var (
	PropertyStatus_name = map[int32]string{
		0: "PROPERTY_STATUS_UNSPECIFIED",
		1: "PROPERTY_STATUS_NEW",
		2: "PROPERTY_STATUS_PUBLISHED",
		3: "PROPERTY_STATUS_SOLD",
		4: "PROPERTY_STATUS_DELETED",
	}
	PropertyStatus_value = map[string]int32{
		"PROPERTY_STATUS_UNSPECIFIED": 0,
		"PROPERTY_STATUS_NEW":         1,
		"PROPERTY_STATUS_PUBLISHED":   2,
		"PROPERTY_STATUS_SOLD":        3,
		"PROPERTY_STATUS_DELETED":     4,
	}
)

func (x PropertyStatus) Enum() *PropertyStatus {
	p := new(PropertyStatus)
	*p = x
	return p
}

func (x PropertyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_property_proto_enumTypes[1].Descriptor()
}

func (PropertyStatus) Type() protoreflect.EnumType {
	return &file_property_proto_enumTypes[1]
}

func (x PropertyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyStatus.Descriptor instead.
func (PropertyStatus) EnumDescriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{1}
}

// Property — сущность объекта недвижимости.
type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PropertyType  PropertyType           `protobuf:"varint,5,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType" json:"property_type,omitempty"`
	Area          *float64               `protobuf:"fixed64,6,opt,name=area,proto3,oneof" json:"area,omitempty"`
	Price         *int64                 `protobuf:"varint,7,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Rooms         *int32                 `protobuf:"varint,8,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	Status        PropertyStatus         `protobuf:"varint,9,opt,name=status,proto3,enum=leadexchange.v1.PropertyStatus" json:"status,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,10,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	CreatedUserId string                 `protobuf:"bytes,11,opt,name=created_user_id,json=createdUserId,proto3" json:"created_user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	City          *string                `protobuf:"bytes,14,opt,name=city,proto3,oneof" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_property_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *Property) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Property) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Property) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Property) GetPropertyType() PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *Property) GetArea() float64 {
	if x != nil && x.Area != nil {
		return *x.Area
	}
	return 0
}

func (x *Property) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *Property) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

func (x *Property) GetStatus() PropertyStatus {
	if x != nil {
		return x.Status
	}
	return PropertyStatus_PROPERTY_STATUS_UNSPECIFIED
}

func (x *Property) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Property) GetCreatedUserId() string {
	if x != nil {
		return x.CreatedUserId
	}
	return ""
}

func (x *Property) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Property) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Property) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

type CreatePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PropertyType  PropertyType           `protobuf:"varint,4,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType" json:"property_type,omitempty"`
	Area          *float64               `protobuf:"fixed64,5,opt,name=area,proto3,oneof" json:"area,omitempty"`
	Price         *int64                 `protobuf:"varint,6,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Rooms         *int32                 `protobuf:"varint,7,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	City          *string                `protobuf:"bytes,8,opt,name=city,proto3,oneof" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePropertyRequest) Reset() {
	*x = CreatePropertyRequest{}
	mi := &file_property_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePropertyRequest) ProtoMessage() {}

func (x *CreatePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePropertyRequest.ProtoReflect.Descriptor instead.
func (*CreatePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePropertyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePropertyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePropertyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreatePropertyRequest) GetPropertyType() PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *CreatePropertyRequest) GetArea() float64 {
	if x != nil && x.Area != nil {
		return *x.Area
	}
	return 0
}

func (x *CreatePropertyRequest) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *CreatePropertyRequest) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

func (x *CreatePropertyRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

type GetPropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertyRequest) Reset() {
	*x = GetPropertyRequest{}
	mi := &file_property_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyRequest) ProtoMessage() {}

func (x *GetPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyRequest.ProtoReflect.Descriptor instead.
func (*GetPropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{2}
}

func (x *GetPropertyRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

type ListPropertiesRequest struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	Filter         *ListPropertiesRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize       *int32                        `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken      *string                       `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	OrderBy        *string                       `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	OrderDirection *string                       `protobuf:"bytes,5,opt,name=order_direction,json=orderDirection,proto3,oneof" json:"order_direction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPropertiesRequest) Reset() {
	*x = ListPropertiesRequest{}
	mi := &file_property_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesRequest) ProtoMessage() {}

func (x *ListPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesRequest.ProtoReflect.Descriptor instead.
func (*ListPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{3}
}

func (x *ListPropertiesRequest) GetFilter() *ListPropertiesRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListPropertiesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListPropertiesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListPropertiesRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListPropertiesRequest) GetOrderDirection() string {
	if x != nil && x.OrderDirection != nil {
		return *x.OrderDirection
	}
	return ""
}

type ListPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    []*Property            `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertiesResponse) Reset() {
	*x = ListPropertiesResponse{}
	mi := &file_property_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesResponse) ProtoMessage() {}

func (x *ListPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesResponse.ProtoReflect.Descriptor instead.
func (*ListPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{4}
}

func (x *ListPropertiesResponse) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UpdatePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Address       *string                `protobuf:"bytes,4,opt,name=address,proto3,oneof" json:"address,omitempty"`
	PropertyType  *PropertyType          `protobuf:"varint,5,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType,oneof" json:"property_type,omitempty"`
	Area          *float64               `protobuf:"fixed64,6,opt,name=area,proto3,oneof" json:"area,omitempty"`
	Price         *int64                 `protobuf:"varint,7,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Rooms         *int32                 `protobuf:"varint,8,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	Status        *PropertyStatus        `protobuf:"varint,9,opt,name=status,proto3,enum=leadexchange.v1.PropertyStatus,oneof" json:"status,omitempty"`
	OwnerUserId   *string                `protobuf:"bytes,10,opt,name=owner_user_id,json=ownerUserId,proto3,oneof" json:"owner_user_id,omitempty"`
	City          *string                `protobuf:"bytes,11,opt,name=city,proto3,oneof" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePropertyRequest) Reset() {
	*x = UpdatePropertyRequest{}
	mi := &file_property_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePropertyRequest) ProtoMessage() {}

func (x *UpdatePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePropertyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePropertyRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *UpdatePropertyRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdatePropertyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdatePropertyRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UpdatePropertyRequest) GetPropertyType() PropertyType {
	if x != nil && x.PropertyType != nil {
		return *x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *UpdatePropertyRequest) GetArea() float64 {
	if x != nil && x.Area != nil {
		return *x.Area
	}
	return 0
}

func (x *UpdatePropertyRequest) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdatePropertyRequest) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

func (x *UpdatePropertyRequest) GetStatus() PropertyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PropertyStatus_PROPERTY_STATUS_UNSPECIFIED
}

func (x *UpdatePropertyRequest) GetOwnerUserId() string {
	if x != nil && x.OwnerUserId != nil {
		return *x.OwnerUserId
	}
	return ""
}

func (x *UpdatePropertyRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

type PropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Property      *Property              `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyResponse) Reset() {
	*x = PropertyResponse{}
	mi := &file_property_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyResponse) ProtoMessage() {}

func (x *PropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyResponse.ProtoReflect.Descriptor instead.
func (*PropertyResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{6}
}

func (x *PropertyResponse) GetProperty() *Property {
	if x != nil {
		return x.Property
	}
	return nil
}

// MatchPropertiesRequest — запрос на поиск подходящих объектов для лида.
type MatchPropertiesRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	LeadId        string                         `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Filter        *MatchPropertiesRequest_Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         *int32                         `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchPropertiesRequest) Reset() {
	*x = MatchPropertiesRequest{}
	mi := &file_property_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPropertiesRequest) ProtoMessage() {}

func (x *MatchPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPropertiesRequest.ProtoReflect.Descriptor instead.
func (*MatchPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{7}
}

func (x *MatchPropertiesRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *MatchPropertiesRequest) GetFilter() *MatchPropertiesRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *MatchPropertiesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

// MatchedProperty — объект недвижимости с коэффициентом схожести.
type MatchedProperty struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Property   *Property              `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	Similarity float64                `protobuf:"fixed64,2,opt,name=similarity,proto3" json:"similarity,omitempty"`
	// Взвешенные scores
	TotalScore       *float64 `protobuf:"fixed64,3,opt,name=total_score,json=totalScore,proto3,oneof" json:"total_score,omitempty"`
	PriceScore       *float64 `protobuf:"fixed64,4,opt,name=price_score,json=priceScore,proto3,oneof" json:"price_score,omitempty"`
	DistrictScore    *float64 `protobuf:"fixed64,5,opt,name=district_score,json=districtScore,proto3,oneof" json:"district_score,omitempty"`
	RoomsScore       *float64 `protobuf:"fixed64,6,opt,name=rooms_score,json=roomsScore,proto3,oneof" json:"rooms_score,omitempty"`
	AreaScore        *float64 `protobuf:"fixed64,7,opt,name=area_score,json=areaScore,proto3,oneof" json:"area_score,omitempty"`
	SemanticScore    *float64 `protobuf:"fixed64,8,opt,name=semantic_score,json=semanticScore,proto3,oneof" json:"semantic_score,omitempty"`
	MatchExplanation *string  `protobuf:"bytes,9,opt,name=match_explanation,json=matchExplanation,proto3,oneof" json:"match_explanation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MatchedProperty) Reset() {
	*x = MatchedProperty{}
	mi := &file_property_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchedProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedProperty) ProtoMessage() {}

func (x *MatchedProperty) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchedProperty.ProtoReflect.Descriptor instead.
func (*MatchedProperty) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{8}
}

func (x *MatchedProperty) GetProperty() *Property {
	if x != nil {
		return x.Property
	}
	return nil
}

func (x *MatchedProperty) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *MatchedProperty) GetTotalScore() float64 {
	if x != nil && x.TotalScore != nil {
		return *x.TotalScore
	}
	return 0
}

func (x *MatchedProperty) GetPriceScore() float64 {
	if x != nil && x.PriceScore != nil {
		return *x.PriceScore
	}
	return 0
}

func (x *MatchedProperty) GetDistrictScore() float64 {
	if x != nil && x.DistrictScore != nil {
		return *x.DistrictScore
	}
	return 0
}

func (x *MatchedProperty) GetRoomsScore() float64 {
	if x != nil && x.RoomsScore != nil {
		return *x.RoomsScore
	}
	return 0
}

func (x *MatchedProperty) GetAreaScore() float64 {
	if x != nil && x.AreaScore != nil {
		return *x.AreaScore
	}
	return 0
}

func (x *MatchedProperty) GetSemanticScore() float64 {
	if x != nil && x.SemanticScore != nil {
		return *x.SemanticScore
	}
	return 0
}

func (x *MatchedProperty) GetMatchExplanation() string {
	if x != nil && x.MatchExplanation != nil {
		return *x.MatchExplanation
	}
	return ""
}

// MatchPropertiesResponse — ответ с подходящими объектами.
type MatchPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*MatchedProperty     `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchPropertiesResponse) Reset() {
	*x = MatchPropertiesResponse{}
	mi := &file_property_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPropertiesResponse) ProtoMessage() {}

func (x *MatchPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPropertiesResponse.ProtoReflect.Descriptor instead.
func (*MatchPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{9}
}

func (x *MatchPropertiesResponse) GetMatches() []*MatchedProperty {
	if x != nil {
		return x.Matches
	}
	return nil
}

type ReindexPropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexPropertyRequest) Reset() {
	*x = ReindexPropertyRequest{}
	mi := &file_property_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexPropertyRequest) ProtoMessage() {}

func (x *ReindexPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexPropertyRequest.ProtoReflect.Descriptor instead.
func (*ReindexPropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{10}
}

func (x *ReindexPropertyRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

type ReindexPropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexPropertyResponse) Reset() {
	*x = ReindexPropertyResponse{}
	mi := &file_property_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexPropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexPropertyResponse) ProtoMessage() {}

func (x *ReindexPropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexPropertyResponse.ProtoReflect.Descriptor instead.
func (*ReindexPropertyResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{11}
}

func (x *ReindexPropertyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReindexPropertyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PropertyFilter — фильтр для поиска объектов.
type PropertyFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          *string                `protobuf:"bytes,1,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Status        *PropertyStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=leadexchange.v1.PropertyStatus,oneof" json:"status,omitempty"`
	PropertyType  *PropertyType          `protobuf:"varint,3,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType,oneof" json:"property_type,omitempty"`
	MinPrice      *int64                 `protobuf:"varint,4,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *int64                 `protobuf:"varint,5,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	MinRooms      *int32                 `protobuf:"varint,6,opt,name=min_rooms,json=minRooms,proto3,oneof" json:"min_rooms,omitempty"`
	MaxRooms      *int32                 `protobuf:"varint,7,opt,name=max_rooms,json=maxRooms,proto3,oneof" json:"max_rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyFilter) Reset() {
	*x = PropertyFilter{}
	mi := &file_property_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyFilter) ProtoMessage() {}

func (x *PropertyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyFilter.ProtoReflect.Descriptor instead.
func (*PropertyFilter) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{12}
}

func (x *PropertyFilter) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *PropertyFilter) GetStatus() PropertyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PropertyStatus_PROPERTY_STATUS_UNSPECIFIED
}

func (x *PropertyFilter) GetPropertyType() PropertyType {
	if x != nil && x.PropertyType != nil {
		return *x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *PropertyFilter) GetMinPrice() int64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *PropertyFilter) GetMaxPrice() int64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

func (x *PropertyFilter) GetMinRooms() int32 {
	if x != nil && x.MinRooms != nil {
		return *x.MinRooms
	}
	return 0
}

func (x *PropertyFilter) GetMaxRooms() int32 {
	if x != nil && x.MaxRooms != nil {
		return *x.MaxRooms
	}
	return 0
}

// MatchPropertiesAdvancedRequest — запрос на расширенный поиск.
type MatchPropertiesAdvancedRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LeadId            string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Filter            *PropertyFilter        `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit             *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	UseHybridSearch   *bool                  `protobuf:"varint,4,opt,name=use_hybrid_search,json=useHybridSearch,proto3,oneof" json:"use_hybrid_search,omitempty"`
	UseReranker       *bool                  `protobuf:"varint,5,opt,name=use_reranker,json=useReranker,proto3,oneof" json:"use_reranker,omitempty"`
	UseDynamicWeights *bool                  `protobuf:"varint,6,opt,name=use_dynamic_weights,json=useDynamicWeights,proto3,oneof" json:"use_dynamic_weights,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MatchPropertiesAdvancedRequest) Reset() {
	*x = MatchPropertiesAdvancedRequest{}
	mi := &file_property_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPropertiesAdvancedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPropertiesAdvancedRequest) ProtoMessage() {}

func (x *MatchPropertiesAdvancedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPropertiesAdvancedRequest.ProtoReflect.Descriptor instead.
func (*MatchPropertiesAdvancedRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{13}
}

func (x *MatchPropertiesAdvancedRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *MatchPropertiesAdvancedRequest) GetFilter() *PropertyFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *MatchPropertiesAdvancedRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *MatchPropertiesAdvancedRequest) GetUseHybridSearch() bool {
	if x != nil && x.UseHybridSearch != nil {
		return *x.UseHybridSearch
	}
	return false
}

func (x *MatchPropertiesAdvancedRequest) GetUseReranker() bool {
	if x != nil && x.UseReranker != nil {
		return *x.UseReranker
	}
	return false
}

func (x *MatchPropertiesAdvancedRequest) GetUseDynamicWeights() bool {
	if x != nil && x.UseDynamicWeights != nil {
		return *x.UseDynamicWeights
	}
	return false
}

type GetPropertyJSONLDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	BaseUrl       *string                `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3,oneof" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertyJSONLDRequest) Reset() {
	*x = GetPropertyJSONLDRequest{}
	mi := &file_property_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertyJSONLDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyJSONLDRequest) ProtoMessage() {}

func (x *GetPropertyJSONLDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyJSONLDRequest.ProtoReflect.Descriptor instead.
func (*GetPropertyJSONLDRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{14}
}

func (x *GetPropertyJSONLDRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *GetPropertyJSONLDRequest) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

type GetPropertyJSONLDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonldData    []byte                 `protobuf:"bytes,1,opt,name=jsonld_data,json=jsonldData,proto3" json:"jsonld_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertyJSONLDResponse) Reset() {
	*x = GetPropertyJSONLDResponse{}
	mi := &file_property_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertyJSONLDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyJSONLDResponse) ProtoMessage() {}

func (x *GetPropertyJSONLDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyJSONLDResponse.ProtoReflect.Descriptor instead.
func (*GetPropertyJSONLDResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{15}
}

func (x *GetPropertyJSONLDResponse) GetJsonldData() []byte {
	if x != nil {
		return x.JsonldData
	}
	return nil
}

type GenerateListingContentRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PropertyId          *string                `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3,oneof" json:"property_id,omitempty"`
	PropertyType        *string                `protobuf:"bytes,2,opt,name=property_type,json=propertyType,proto3,oneof" json:"property_type,omitempty"`
	Address             *string                `protobuf:"bytes,3,opt,name=address,proto3,oneof" json:"address,omitempty"`
	City                *string                `protobuf:"bytes,4,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Price               *int64                 `protobuf:"varint,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Rooms               *int32                 `protobuf:"varint,6,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	Area                *float64               `protobuf:"fixed64,7,opt,name=area,proto3,oneof" json:"area,omitempty"`
	ExistingTitle       *string                `protobuf:"bytes,8,opt,name=existing_title,json=existingTitle,proto3,oneof" json:"existing_title,omitempty"`
	ExistingDescription *string                `protobuf:"bytes,9,opt,name=existing_description,json=existingDescription,proto3,oneof" json:"existing_description,omitempty"`
	Features            []string               `protobuf:"bytes,10,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GenerateListingContentRequest) Reset() {
	*x = GenerateListingContentRequest{}
	mi := &file_property_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateListingContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateListingContentRequest) ProtoMessage() {}

func (x *GenerateListingContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateListingContentRequest.ProtoReflect.Descriptor instead.
func (*GenerateListingContentRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{16}
}

func (x *GenerateListingContentRequest) GetPropertyId() string {
	if x != nil && x.PropertyId != nil {
		return *x.PropertyId
	}
	return ""
}

func (x *GenerateListingContentRequest) GetPropertyType() string {
	if x != nil && x.PropertyType != nil {
		return *x.PropertyType
	}
	return ""
}

func (x *GenerateListingContentRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *GenerateListingContentRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *GenerateListingContentRequest) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *GenerateListingContentRequest) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

func (x *GenerateListingContentRequest) GetArea() float64 {
	if x != nil && x.Area != nil {
		return *x.Area
	}
	return 0
}

func (x *GenerateListingContentRequest) GetExistingTitle() string {
	if x != nil && x.ExistingTitle != nil {
		return *x.ExistingTitle
	}
	return ""
}

func (x *GenerateListingContentRequest) GetExistingDescription() string {
	if x != nil && x.ExistingDescription != nil {
		return *x.ExistingDescription
	}
	return ""
}

func (x *GenerateListingContentRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type GenerateListingContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Keywords      []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateListingContentResponse) Reset() {
	*x = GenerateListingContentResponse{}
	mi := &file_property_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateListingContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateListingContentResponse) ProtoMessage() {}

func (x *GenerateListingContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateListingContentResponse.ProtoReflect.Descriptor instead.
func (*GenerateListingContentResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{17}
}

func (x *GenerateListingContentResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GenerateListingContentResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GenerateListingContentResponse) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *GenerateListingContentResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type AnalyzePropertyImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,2,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzePropertyImagesRequest) Reset() {
	*x = AnalyzePropertyImagesRequest{}
	mi := &file_property_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzePropertyImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzePropertyImagesRequest) ProtoMessage() {}

func (x *AnalyzePropertyImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzePropertyImagesRequest.ProtoReflect.Descriptor instead.
func (*AnalyzePropertyImagesRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{18}
}

func (x *AnalyzePropertyImagesRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *AnalyzePropertyImagesRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type ImageFeature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageFeature) Reset() {
	*x = ImageFeature{}
	mi := &file_property_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageFeature) ProtoMessage() {}

func (x *ImageFeature) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageFeature.ProtoReflect.Descriptor instead.
func (*ImageFeature) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{19}
}

func (x *ImageFeature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageFeature) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ImageFeature) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ImageAnalysisResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DetectedFeatures []*ImageFeature        `protobuf:"bytes,1,rep,name=detected_features,json=detectedFeatures,proto3" json:"detected_features,omitempty"`
	RoomType         *string                `protobuf:"bytes,2,opt,name=room_type,json=roomType,proto3,oneof" json:"room_type,omitempty"`
	QualityScore     float64                `protobuf:"fixed64,3,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	ViewType         *string                `protobuf:"bytes,4,opt,name=view_type,json=viewType,proto3,oneof" json:"view_type,omitempty"`
	Brightness       float64                `protobuf:"fixed64,5,opt,name=brightness,proto3" json:"brightness,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ImageAnalysisResult) Reset() {
	*x = ImageAnalysisResult{}
	mi := &file_property_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageAnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageAnalysisResult) ProtoMessage() {}

func (x *ImageAnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageAnalysisResult.ProtoReflect.Descriptor instead.
func (*ImageAnalysisResult) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{20}
}

func (x *ImageAnalysisResult) GetDetectedFeatures() []*ImageFeature {
	if x != nil {
		return x.DetectedFeatures
	}
	return nil
}

func (x *ImageAnalysisResult) GetRoomType() string {
	if x != nil && x.RoomType != nil {
		return *x.RoomType
	}
	return ""
}

func (x *ImageAnalysisResult) GetQualityScore() float64 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *ImageAnalysisResult) GetViewType() string {
	if x != nil && x.ViewType != nil {
		return *x.ViewType
	}
	return ""
}

func (x *ImageAnalysisResult) GetBrightness() float64 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type AnalyzePropertyImagesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalImages       int32                  `protobuf:"varint,1,opt,name=total_images,json=totalImages,proto3" json:"total_images,omitempty"`
	AverageQuality    float64                `protobuf:"fixed64,2,opt,name=average_quality,json=averageQuality,proto3" json:"average_quality,omitempty"`
	DetectedRooms     []string               `protobuf:"bytes,3,rep,name=detected_rooms,json=detectedRooms,proto3" json:"detected_rooms,omitempty"`
	AllFeatures       []*ImageFeature        `protobuf:"bytes,4,rep,name=all_features,json=allFeatures,proto3" json:"all_features,omitempty"`
	ViewTypes         []string               `protobuf:"bytes,5,rep,name=view_types,json=viewTypes,proto3" json:"view_types,omitempty"`
	OverallAssessment string                 `protobuf:"bytes,6,opt,name=overall_assessment,json=overallAssessment,proto3" json:"overall_assessment,omitempty"`
	ImageResults      []*ImageAnalysisResult `protobuf:"bytes,7,rep,name=image_results,json=imageResults,proto3" json:"image_results,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AnalyzePropertyImagesResponse) Reset() {
	*x = AnalyzePropertyImagesResponse{}
	mi := &file_property_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzePropertyImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzePropertyImagesResponse) ProtoMessage() {}

func (x *AnalyzePropertyImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzePropertyImagesResponse.ProtoReflect.Descriptor instead.
func (*AnalyzePropertyImagesResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{21}
}

func (x *AnalyzePropertyImagesResponse) GetTotalImages() int32 {
	if x != nil {
		return x.TotalImages
	}
	return 0
}

func (x *AnalyzePropertyImagesResponse) GetAverageQuality() float64 {
	if x != nil {
		return x.AverageQuality
	}
	return 0
}

func (x *AnalyzePropertyImagesResponse) GetDetectedRooms() []string {
	if x != nil {
		return x.DetectedRooms
	}
	return nil
}

func (x *AnalyzePropertyImagesResponse) GetAllFeatures() []*ImageFeature {
	if x != nil {
		return x.AllFeatures
	}
	return nil
}

func (x *AnalyzePropertyImagesResponse) GetViewTypes() []string {
	if x != nil {
		return x.ViewTypes
	}
	return nil
}

func (x *AnalyzePropertyImagesResponse) GetOverallAssessment() string {
	if x != nil {
		return x.OverallAssessment
	}
	return ""
}

func (x *AnalyzePropertyImagesResponse) GetImageResults() []*ImageAnalysisResult {
	if x != nil {
		return x.ImageResults
	}
	return nil
}

type ListPropertiesRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *PropertyStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=leadexchange.v1.PropertyStatus,oneof" json:"status,omitempty"`
	OwnerUserId   *string                `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3,oneof" json:"owner_user_id,omitempty"`
	CreatedUserId *string                `protobuf:"bytes,3,opt,name=created_user_id,json=createdUserId,proto3,oneof" json:"created_user_id,omitempty"`
	PropertyType  *PropertyType          `protobuf:"varint,4,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType,oneof" json:"property_type,omitempty"`
	MinRooms      *int32                 `protobuf:"varint,5,opt,name=min_rooms,json=minRooms,proto3,oneof" json:"min_rooms,omitempty"`
	MaxRooms      *int32                 `protobuf:"varint,6,opt,name=max_rooms,json=maxRooms,proto3,oneof" json:"max_rooms,omitempty"`
	MinPrice      *int64                 `protobuf:"varint,7,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *int64                 `protobuf:"varint,8,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	City          *string                `protobuf:"bytes,9,opt,name=city,proto3,oneof" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertiesRequest_Filter) Reset() {
	*x = ListPropertiesRequest_Filter{}
	mi := &file_property_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesRequest_Filter) ProtoMessage() {}

func (x *ListPropertiesRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListPropertiesRequest_Filter) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListPropertiesRequest_Filter) GetStatus() PropertyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PropertyStatus_PROPERTY_STATUS_UNSPECIFIED
}

func (x *ListPropertiesRequest_Filter) GetOwnerUserId() string {
	if x != nil && x.OwnerUserId != nil {
		return *x.OwnerUserId
	}
	return ""
}

func (x *ListPropertiesRequest_Filter) GetCreatedUserId() string {
	if x != nil && x.CreatedUserId != nil {
		return *x.CreatedUserId
	}
	return ""
}

func (x *ListPropertiesRequest_Filter) GetPropertyType() PropertyType {
	if x != nil && x.PropertyType != nil {
		return *x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *ListPropertiesRequest_Filter) GetMinRooms() int32 {
	if x != nil && x.MinRooms != nil {
		return *x.MinRooms
	}
	return 0
}

func (x *ListPropertiesRequest_Filter) GetMaxRooms() int32 {
	if x != nil && x.MaxRooms != nil {
		return *x.MaxRooms
	}
	return 0
}

func (x *ListPropertiesRequest_Filter) GetMinPrice() int64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *ListPropertiesRequest_Filter) GetMaxPrice() int64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

func (x *ListPropertiesRequest_Filter) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

type MatchPropertiesRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *PropertyStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=leadexchange.v1.PropertyStatus,oneof" json:"status,omitempty"`
	PropertyType  *PropertyType          `protobuf:"varint,2,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType,oneof" json:"property_type,omitempty"`
	MinRooms      *int32                 `protobuf:"varint,3,opt,name=min_rooms,json=minRooms,proto3,oneof" json:"min_rooms,omitempty"`
	MaxRooms      *int32                 `protobuf:"varint,4,opt,name=max_rooms,json=maxRooms,proto3,oneof" json:"max_rooms,omitempty"`
	MinPrice      *int64                 `protobuf:"varint,5,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *int64                 `protobuf:"varint,6,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	City          *string                `protobuf:"bytes,7,opt,name=city,proto3,oneof" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchPropertiesRequest_Filter) Reset() {
	*x = MatchPropertiesRequest_Filter{}
	mi := &file_property_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPropertiesRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPropertiesRequest_Filter) ProtoMessage() {}

func (x *MatchPropertiesRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPropertiesRequest_Filter.ProtoReflect.Descriptor instead.
func (*MatchPropertiesRequest_Filter) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{7, 0}
}

func (x *MatchPropertiesRequest_Filter) GetStatus() PropertyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PropertyStatus_PROPERTY_STATUS_UNSPECIFIED
}

func (x *MatchPropertiesRequest_Filter) GetPropertyType() PropertyType {
	if x != nil && x.PropertyType != nil {
		return *x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *MatchPropertiesRequest_Filter) GetMinRooms() int32 {
	if x != nil && x.MinRooms != nil {
		return *x.MinRooms
	}
	return 0
}

func (x *MatchPropertiesRequest_Filter) GetMaxRooms() int32 {
	if x != nil && x.MaxRooms != nil {
		return *x.MaxRooms
	}
	return 0
}

func (x *MatchPropertiesRequest_Filter) GetMinPrice() int64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *MatchPropertiesRequest_Filter) GetMaxPrice() int64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

func (x *MatchPropertiesRequest_Filter) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

var File_property_proto protoreflect.FileDescriptor

const file_property_proto_rawDesc = "" +
	"\n" +
	"\x0eproperty.proto\x12\x0fleadexchange.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xb8\x04\n" +
	"\bProperty\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\aaddress\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x05R\aaddress\x12B\n" +
	"\rproperty_type\x18\x05 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeR\fpropertyType\x12\x17\n" +
	"\x04area\x18\x06 \x01(\x01H\x00R\x04area\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\a \x01(\x03H\x01R\x05price\x88\x01\x01\x12\x19\n" +
	"\x05rooms\x18\b \x01(\x05H\x02R\x05rooms\x88\x01\x01\x127\n" +
	"\x06status\x18\t \x01(\x0e2\x1f.leadexchange.v1.PropertyStatusR\x06status\x12,\n" +
	"\rowner_user_id\x18\n" +
	" \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\vownerUserId\x120\n" +
	"\x0fcreated_user_id\x18\v \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\rcreatedUserId\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12\x17\n" +
	"\x04city\x18\x0e \x01(\tH\x03R\x04city\x88\x01\x01B\a\n" +
	"\x05_areaB\b\n" +
	"\x06_priceB\b\n" +
	"\x06_roomsB\a\n" +
	"\x05_city\"\xd7\x02\n" +
	"\x15CreatePropertyRequest\x12\x1d\n" +
	"\x05title\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\aaddress\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x05R\aaddress\x12L\n" +
	"\rproperty_type\x18\x04 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\fpropertyType\x12\x17\n" +
	"\x04area\x18\x05 \x01(\x01H\x00R\x04area\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x06 \x01(\x03H\x01R\x05price\x88\x01\x01\x12\x19\n" +
	"\x05rooms\x18\a \x01(\x05H\x02R\x05rooms\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\b \x01(\tH\x03R\x04city\x88\x01\x01B\a\n" +
	"\x05_areaB\b\n" +
	"\x06_priceB\b\n" +
	"\x06_roomsB\a\n" +
	"\x05_city\"?\n" +
	"\x12GetPropertyRequest\x12)\n" +
	"\vproperty_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"propertyId\"\xbd\x06\n" +
	"\x15ListPropertiesRequest\x12E\n" +
	"\x06filter\x18\x01 \x01(\v2-.leadexchange.v1.ListPropertiesRequest.FilterR\x06filter\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tH\x01R\tpageToken\x88\x01\x01\x12\x1e\n" +
	"\border_by\x18\x04 \x01(\tH\x02R\aorderBy\x88\x01\x01\x12,\n" +
	"\x0forder_direction\x18\x05 \x01(\tH\x03R\x0eorderDirection\x88\x01\x01\x1a\x8a\x04\n" +
	"\x06Filter\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.leadexchange.v1.PropertyStatusH\x00R\x06status\x88\x01\x01\x12'\n" +
	"\rowner_user_id\x18\x02 \x01(\tH\x01R\vownerUserId\x88\x01\x01\x12+\n" +
	"\x0fcreated_user_id\x18\x03 \x01(\tH\x02R\rcreatedUserId\x88\x01\x01\x12G\n" +
	"\rproperty_type\x18\x04 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeH\x03R\fpropertyType\x88\x01\x01\x12 \n" +
	"\tmin_rooms\x18\x05 \x01(\x05H\x04R\bminRooms\x88\x01\x01\x12 \n" +
	"\tmax_rooms\x18\x06 \x01(\x05H\x05R\bmaxRooms\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\a \x01(\x03H\x06R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\b \x01(\x03H\aR\bmaxPrice\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\t \x01(\tH\bR\x04city\x88\x01\x01B\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_owner_user_idB\x12\n" +
	"\x10_created_user_idB\x10\n" +
	"\x0e_property_typeB\f\n" +
	"\n" +
	"_min_roomsB\f\n" +
	"\n" +
	"_max_roomsB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_priceB\a\n" +
	"\x05_cityB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\v\n" +
	"\t_order_byB\x12\n" +
	"\x10_order_direction\"S\n" +
	"\x16ListPropertiesResponse\x129\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2\x19.leadexchange.v1.PropertyR\n" +
	"properties\"\xb6\x04\n" +
	"\x15UpdatePropertyRequest\x12)\n" +
	"\vproperty_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"propertyId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x04 \x01(\tH\x02R\aaddress\x88\x01\x01\x12G\n" +
	"\rproperty_type\x18\x05 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeH\x03R\fpropertyType\x88\x01\x01\x12\x17\n" +
	"\x04area\x18\x06 \x01(\x01H\x04R\x04area\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\a \x01(\x03H\x05R\x05price\x88\x01\x01\x12\x19\n" +
	"\x05rooms\x18\b \x01(\x05H\x06R\x05rooms\x88\x01\x01\x12<\n" +
	"\x06status\x18\t \x01(\x0e2\x1f.leadexchange.v1.PropertyStatusH\aR\x06status\x88\x01\x01\x12'\n" +
	"\rowner_user_id\x18\n" +
	" \x01(\tH\bR\vownerUserId\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\v \x01(\tH\tR\x04city\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_addressB\x10\n" +
	"\x0e_property_typeB\a\n" +
	"\x05_areaB\b\n" +
	"\x06_priceB\b\n" +
	"\x06_roomsB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_owner_user_idB\a\n" +
	"\x05_city\"I\n" +
	"\x10PropertyResponse\x125\n" +
	"\bproperty\x18\x01 \x01(\v2\x19.leadexchange.v1.PropertyR\bproperty\"\xb9\x04\n" +
	"\x16MatchPropertiesRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\x12F\n" +
	"\x06filter\x18\x02 \x01(\v2..leadexchange.v1.MatchPropertiesRequest.FilterR\x06filter\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x00R\x05limit\x88\x01\x01\x1a\x8e\x03\n" +
	"\x06Filter\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.leadexchange.v1.PropertyStatusH\x00R\x06status\x88\x01\x01\x12G\n" +
	"\rproperty_type\x18\x02 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeH\x01R\fpropertyType\x88\x01\x01\x12 \n" +
	"\tmin_rooms\x18\x03 \x01(\x05H\x02R\bminRooms\x88\x01\x01\x12 \n" +
	"\tmax_rooms\x18\x04 \x01(\x05H\x03R\bmaxRooms\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x05 \x01(\x03H\x04R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\x06 \x01(\x03H\x05R\bmaxPrice\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\a \x01(\tH\x06R\x04city\x88\x01\x01B\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_property_typeB\f\n" +
	"\n" +
	"_min_roomsB\f\n" +
	"\n" +
	"_max_roomsB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_priceB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_limit\"\x83\x04\n" +
	"\x0fMatchedProperty\x125\n" +
	"\bproperty\x18\x01 \x01(\v2\x19.leadexchange.v1.PropertyR\bproperty\x12\x1e\n" +
	"\n" +
	"similarity\x18\x02 \x01(\x01R\n" +
	"similarity\x12$\n" +
	"\vtotal_score\x18\x03 \x01(\x01H\x00R\n" +
	"totalScore\x88\x01\x01\x12$\n" +
	"\vprice_score\x18\x04 \x01(\x01H\x01R\n" +
	"priceScore\x88\x01\x01\x12*\n" +
	"\x0edistrict_score\x18\x05 \x01(\x01H\x02R\rdistrictScore\x88\x01\x01\x12$\n" +
	"\vrooms_score\x18\x06 \x01(\x01H\x03R\n" +
	"roomsScore\x88\x01\x01\x12\"\n" +
	"\n" +
	"area_score\x18\a \x01(\x01H\x04R\tareaScore\x88\x01\x01\x12*\n" +
	"\x0esemantic_score\x18\b \x01(\x01H\x05R\rsemanticScore\x88\x01\x01\x120\n" +
	"\x11match_explanation\x18\t \x01(\tH\x06R\x10matchExplanation\x88\x01\x01B\x0e\n" +
	"\f_total_scoreB\x0e\n" +
	"\f_price_scoreB\x11\n" +
	"\x0f_district_scoreB\x0e\n" +
	"\f_rooms_scoreB\r\n" +
	"\v_area_scoreB\x11\n" +
	"\x0f_semantic_scoreB\x14\n" +
	"\x12_match_explanation\"U\n" +
	"\x17MatchPropertiesResponse\x12:\n" +
	"\amatches\x18\x01 \x03(\v2 .leadexchange.v1.MatchedPropertyR\amatches\"C\n" +
	"\x16ReindexPropertyRequest\x12)\n" +
	"\vproperty_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"propertyId\"M\n" +
	"\x17ReindexPropertyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x96\x03\n" +
	"\x0ePropertyFilter\x12\x17\n" +
	"\x04city\x18\x01 \x01(\tH\x00R\x04city\x88\x01\x01\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.leadexchange.v1.PropertyStatusH\x01R\x06status\x88\x01\x01\x12G\n" +
	"\rproperty_type\x18\x03 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeH\x02R\fpropertyType\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x04 \x01(\x03H\x03R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\x05 \x01(\x03H\x04R\bmaxPrice\x88\x01\x01\x12 \n" +
	"\tmin_rooms\x18\x06 \x01(\x05H\x05R\bminRooms\x88\x01\x01\x12 \n" +
	"\tmax_rooms\x18\a \x01(\x05H\x06R\bmaxRooms\x88\x01\x01B\a\n" +
	"\x05_cityB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_property_typeB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_priceB\f\n" +
	"\n" +
	"_min_roomsB\f\n" +
	"\n" +
	"_max_rooms\"\xee\x02\n" +
	"\x1eMatchPropertiesAdvancedRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\x127\n" +
	"\x06filter\x18\x02 \x01(\v2\x1f.leadexchange.v1.PropertyFilterR\x06filter\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12/\n" +
	"\x11use_hybrid_search\x18\x04 \x01(\bH\x01R\x0fuseHybridSearch\x88\x01\x01\x12&\n" +
	"\fuse_reranker\x18\x05 \x01(\bH\x02R\vuseReranker\x88\x01\x01\x123\n" +
	"\x13use_dynamic_weights\x18\x06 \x01(\bH\x03R\x11useDynamicWeights\x88\x01\x01B\b\n" +
	"\x06_limitB\x14\n" +
	"\x12_use_hybrid_searchB\x0f\n" +
	"\r_use_rerankerB\x16\n" +
	"\x14_use_dynamic_weights\"r\n" +
	"\x18GetPropertyJSONLDRequest\x12)\n" +
	"\vproperty_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"propertyId\x12\x1e\n" +
	"\bbase_url\x18\x02 \x01(\tH\x00R\abaseUrl\x88\x01\x01B\v\n" +
	"\t_base_url\"<\n" +
	"\x19GetPropertyJSONLDResponse\x12\x1f\n" +
	"\vjsonld_data\x18\x01 \x01(\fR\n" +
	"jsonldData\"\xf6\x03\n" +
	"\x1dGenerateListingContentRequest\x12$\n" +
	"\vproperty_id\x18\x01 \x01(\tH\x00R\n" +
	"propertyId\x88\x01\x01\x12(\n" +
	"\rproperty_type\x18\x02 \x01(\tH\x01R\fpropertyType\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x03 \x01(\tH\x02R\aaddress\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x04 \x01(\tH\x03R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x05 \x01(\x03H\x04R\x05price\x88\x01\x01\x12\x19\n" +
	"\x05rooms\x18\x06 \x01(\x05H\x05R\x05rooms\x88\x01\x01\x12\x17\n" +
	"\x04area\x18\a \x01(\x01H\x06R\x04area\x88\x01\x01\x12*\n" +
	"\x0eexisting_title\x18\b \x01(\tH\aR\rexistingTitle\x88\x01\x01\x126\n" +
	"\x14existing_description\x18\t \x01(\tH\bR\x13existingDescription\x88\x01\x01\x12\x1a\n" +
	"\bfeatures\x18\n" +
	" \x03(\tR\bfeaturesB\x0e\n" +
	"\f_property_idB\x10\n" +
	"\x0e_property_typeB\n" +
	"\n" +
	"\b_addressB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_priceB\b\n" +
	"\x06_roomsB\a\n" +
	"\x05_areaB\x11\n" +
	"\x0f_existing_titleB\x17\n" +
	"\x15_existing_description\"\x94\x01\n" +
	"\x1eGenerateListingContentResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\"h\n" +
	"\x1cAnalyzePropertyImagesRequest\x12)\n" +
	"\vproperty_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"propertyId\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x02 \x03(\tR\timageUrls\"^\n" +
	"\fImageFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"\x86\x02\n" +
	"\x13ImageAnalysisResult\x12J\n" +
	"\x11detected_features\x18\x01 \x03(\v2\x1d.leadexchange.v1.ImageFeatureR\x10detectedFeatures\x12 \n" +
	"\troom_type\x18\x02 \x01(\tH\x00R\broomType\x88\x01\x01\x12#\n" +
	"\rquality_score\x18\x03 \x01(\x01R\fqualityScore\x12 \n" +
	"\tview_type\x18\x04 \x01(\tH\x01R\bviewType\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"brightness\x18\x05 \x01(\x01R\n" +
	"brightnessB\f\n" +
	"\n" +
	"_room_typeB\f\n" +
	"\n" +
	"_view_type\"\xed\x02\n" +
	"\x1dAnalyzePropertyImagesResponse\x12!\n" +
	"\ftotal_images\x18\x01 \x01(\x05R\vtotalImages\x12'\n" +
	"\x0faverage_quality\x18\x02 \x01(\x01R\x0eaverageQuality\x12%\n" +
	"\x0edetected_rooms\x18\x03 \x03(\tR\rdetectedRooms\x12@\n" +
	"\fall_features\x18\x04 \x03(\v2\x1d.leadexchange.v1.ImageFeatureR\vallFeatures\x12\x1d\n" +
	"\n" +
	"view_types\x18\x05 \x03(\tR\tviewTypes\x12-\n" +
	"\x12overall_assessment\x18\x06 \x01(\tR\x11overallAssessment\x12I\n" +
	"\rimage_results\x18\a \x03(\v2$.leadexchange.v1.ImageAnalysisResultR\fimageResults*\x99\x01\n" +
	"\fPropertyType\x12\x1d\n" +
	"\x19PROPERTY_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PROPERTY_TYPE_APARTMENT\x10\x01\x12\x17\n" +
	"\x13PROPERTY_TYPE_HOUSE\x10\x02\x12\x1c\n" +
	"\x18PROPERTY_TYPE_COMMERCIAL\x10\x03\x12\x16\n" +
	"\x12PROPERTY_TYPE_LAND\x10\x04*\xa0\x01\n" +
	"\x0ePropertyStatus\x12\x1f\n" +
	"\x1bPROPERTY_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PROPERTY_STATUS_NEW\x10\x01\x12\x1d\n" +
	"\x19PROPERTY_STATUS_PUBLISHED\x10\x02\x12\x18\n" +
	"\x14PROPERTY_STATUS_SOLD\x10\x03\x12\x1b\n" +
	"\x17PROPERTY_STATUS_DELETED\x10\x042\xbc\v\n" +
	"\x0fPropertyService\x12v\n" +
	"\x0eCreateProperty\x12&.leadexchange.v1.CreatePropertyRequest\x1a!.leadexchange.v1.PropertyResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/properties\x12{\n" +
	"\vGetProperty\x12#.leadexchange.v1.GetPropertyRequest\x1a!.leadexchange.v1.PropertyResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/properties/{property_id}\x12y\n" +
	"\x0eListProperties\x12&.leadexchange.v1.ListPropertiesRequest\x1a'.leadexchange.v1.ListPropertiesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/properties\x12\x84\x01\n" +
	"\x0eUpdateProperty\x12&.leadexchange.v1.UpdatePropertyRequest\x1a!.leadexchange.v1.PropertyResponse\"'\x82\xd3\xe4\x93\x02!:\x01*2\x1c/v1/properties/{property_id}\x12\x85\x01\n" +
	"\x0fMatchProperties\x12'.leadexchange.v1.MatchPropertiesRequest\x1a(.leadexchange.v1.MatchPropertiesResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/properties/match\x12\x95\x01\n" +
	"\x0fReindexProperty\x12'.leadexchange.v1.ReindexPropertyRequest\x1a(.leadexchange.v1.ReindexPropertyResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/properties/{property_id}/reindex\x12\x9e\x01\n" +
	"\x17MatchPropertiesAdvanced\x12/.leadexchange.v1.MatchPropertiesAdvancedRequest\x1a(.leadexchange.v1.MatchPropertiesResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/properties/match/advanced\x12\x97\x01\n" +
	"\x11GetPropertyJSONLD\x12).leadexchange.v1.GetPropertyJSONLDRequest\x1a*.leadexchange.v1.GetPropertyJSONLDResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/properties/{property_id}/jsonld\x12\xa5\x01\n" +
	"\x16GenerateListingContent\x12..leadexchange.v1.GenerateListingContentRequest\x1a/.leadexchange.v1.GenerateListingContentResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/properties/generate-content\x12\xae\x01\n" +
	"\x15AnalyzePropertyImages\x12-.leadexchange.v1.AnalyzePropertyImagesRequest\x1a..leadexchange.v1.AnalyzePropertyImagesResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/v1/properties/{property_id}/analyze-imagesB4Z2leadexchange/gen/go/leadexchange/v1;leadexchangev1b\x06proto3"

var (
	file_property_proto_rawDescOnce sync.Once
	file_property_proto_rawDescData []byte
)

func file_property_proto_rawDescGZIP() []byte {
	file_property_proto_rawDescOnce.Do(func() {
		file_property_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_property_proto_rawDesc), len(file_property_proto_rawDesc)))
	})
	return file_property_proto_rawDescData
}

var file_property_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_property_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_property_proto_goTypes = []any{
	(PropertyType)(0),                      // 0: leadexchange.v1.PropertyType
	(PropertyStatus)(0),                    // 1: leadexchange.v1.PropertyStatus
	(*Property)(nil),                       // 2: leadexchange.v1.Property
	(*CreatePropertyRequest)(nil),          // 3: leadexchange.v1.CreatePropertyRequest
	(*GetPropertyRequest)(nil),             // 4: leadexchange.v1.GetPropertyRequest
	(*ListPropertiesRequest)(nil),          // 5: leadexchange.v1.ListPropertiesRequest
	(*ListPropertiesResponse)(nil),         // 6: leadexchange.v1.ListPropertiesResponse
	(*UpdatePropertyRequest)(nil),          // 7: leadexchange.v1.UpdatePropertyRequest
	(*PropertyResponse)(nil),               // 8: leadexchange.v1.PropertyResponse
	(*MatchPropertiesRequest)(nil),         // 9: leadexchange.v1.MatchPropertiesRequest
	(*MatchedProperty)(nil),                // 10: leadexchange.v1.MatchedProperty
	(*MatchPropertiesResponse)(nil),        // 11: leadexchange.v1.MatchPropertiesResponse
	(*ReindexPropertyRequest)(nil),         // 12: leadexchange.v1.ReindexPropertyRequest
	(*ReindexPropertyResponse)(nil),        // 13: leadexchange.v1.ReindexPropertyResponse
	(*PropertyFilter)(nil),                 // 14: leadexchange.v1.PropertyFilter
	(*MatchPropertiesAdvancedRequest)(nil), // 15: leadexchange.v1.MatchPropertiesAdvancedRequest
	(*GetPropertyJSONLDRequest)(nil),       // 16: leadexchange.v1.GetPropertyJSONLDRequest
	(*GetPropertyJSONLDResponse)(nil),      // 17: leadexchange.v1.GetPropertyJSONLDResponse
	(*GenerateListingContentRequest)(nil),  // 18: leadexchange.v1.GenerateListingContentRequest
	(*GenerateListingContentResponse)(nil), // 19: leadexchange.v1.GenerateListingContentResponse
	(*AnalyzePropertyImagesRequest)(nil),   // 20: leadexchange.v1.AnalyzePropertyImagesRequest
	(*ImageFeature)(nil),                   // 21: leadexchange.v1.ImageFeature
	(*ImageAnalysisResult)(nil),            // 22: leadexchange.v1.ImageAnalysisResult
	(*AnalyzePropertyImagesResponse)(nil),  // 23: leadexchange.v1.AnalyzePropertyImagesResponse
	(*ListPropertiesRequest_Filter)(nil),   // 24: leadexchange.v1.ListPropertiesRequest.Filter
	(*MatchPropertiesRequest_Filter)(nil),  // 25: leadexchange.v1.MatchPropertiesRequest.Filter
}
var file_property_proto_depIdxs = []int32{
	0,  // 0: leadexchange.v1.Property.property_type:type_name -> leadexchange.v1.PropertyType
	1,  // 1: leadexchange.v1.Property.status:type_name -> leadexchange.v1.PropertyStatus
	0,  // 2: leadexchange.v1.CreatePropertyRequest.property_type:type_name -> leadexchange.v1.PropertyType
	24, // 3: leadexchange.v1.ListPropertiesRequest.filter:type_name -> leadexchange.v1.ListPropertiesRequest.Filter
	2,  // 4: leadexchange.v1.ListPropertiesResponse.properties:type_name -> leadexchange.v1.Property
	0,  // 5: leadexchange.v1.UpdatePropertyRequest.property_type:type_name -> leadexchange.v1.PropertyType
	1,  // 6: leadexchange.v1.UpdatePropertyRequest.status:type_name -> leadexchange.v1.PropertyStatus
	2,  // 7: leadexchange.v1.PropertyResponse.property:type_name -> leadexchange.v1.Property
	25, // 8: leadexchange.v1.MatchPropertiesRequest.filter:type_name -> leadexchange.v1.MatchPropertiesRequest.Filter
	2,  // 9: leadexchange.v1.MatchedProperty.property:type_name -> leadexchange.v1.Property
	10, // 10: leadexchange.v1.MatchPropertiesResponse.matches:type_name -> leadexchange.v1.MatchedProperty
	1,  // 11: leadexchange.v1.PropertyFilter.status:type_name -> leadexchange.v1.PropertyStatus
	0,  // 12: leadexchange.v1.PropertyFilter.property_type:type_name -> leadexchange.v1.PropertyType
	14, // 13: leadexchange.v1.MatchPropertiesAdvancedRequest.filter:type_name -> leadexchange.v1.PropertyFilter
	21, // 14: leadexchange.v1.ImageAnalysisResult.detected_features:type_name -> leadexchange.v1.ImageFeature
	21, // 15: leadexchange.v1.AnalyzePropertyImagesResponse.all_features:type_name -> leadexchange.v1.ImageFeature
	22, // 16: leadexchange.v1.AnalyzePropertyImagesResponse.image_results:type_name -> leadexchange.v1.ImageAnalysisResult
	1,  // 17: leadexchange.v1.ListPropertiesRequest.Filter.status:type_name -> leadexchange.v1.PropertyStatus
	0,  // 18: leadexchange.v1.ListPropertiesRequest.Filter.property_type:type_name -> leadexchange.v1.PropertyType
	1,  // 19: leadexchange.v1.MatchPropertiesRequest.Filter.status:type_name -> leadexchange.v1.PropertyStatus
	0,  // 20: leadexchange.v1.MatchPropertiesRequest.Filter.property_type:type_name -> leadexchange.v1.PropertyType
	3,  // 21: leadexchange.v1.PropertyService.CreateProperty:input_type -> leadexchange.v1.CreatePropertyRequest
	4,  // 22: leadexchange.v1.PropertyService.GetProperty:input_type -> leadexchange.v1.GetPropertyRequest
	5,  // 23: leadexchange.v1.PropertyService.ListProperties:input_type -> leadexchange.v1.ListPropertiesRequest
	7,  // 24: leadexchange.v1.PropertyService.UpdateProperty:input_type -> leadexchange.v1.UpdatePropertyRequest
	9,  // 25: leadexchange.v1.PropertyService.MatchProperties:input_type -> leadexchange.v1.MatchPropertiesRequest
	12, // 26: leadexchange.v1.PropertyService.ReindexProperty:input_type -> leadexchange.v1.ReindexPropertyRequest
	15, // 27: leadexchange.v1.PropertyService.MatchPropertiesAdvanced:input_type -> leadexchange.v1.MatchPropertiesAdvancedRequest
	16, // 28: leadexchange.v1.PropertyService.GetPropertyJSONLD:input_type -> leadexchange.v1.GetPropertyJSONLDRequest
	18, // 29: leadexchange.v1.PropertyService.GenerateListingContent:input_type -> leadexchange.v1.GenerateListingContentRequest
	20, // 30: leadexchange.v1.PropertyService.AnalyzePropertyImages:input_type -> leadexchange.v1.AnalyzePropertyImagesRequest
	8,  // 31: leadexchange.v1.PropertyService.CreateProperty:output_type -> leadexchange.v1.PropertyResponse
	8,  // 32: leadexchange.v1.PropertyService.GetProperty:output_type -> leadexchange.v1.PropertyResponse
	6,  // 33: leadexchange.v1.PropertyService.ListProperties:output_type -> leadexchange.v1.ListPropertiesResponse
	8,  // 34: leadexchange.v1.PropertyService.UpdateProperty:output_type -> leadexchange.v1.PropertyResponse
	11, // 35: leadexchange.v1.PropertyService.MatchProperties:output_type -> leadexchange.v1.MatchPropertiesResponse
	13, // 36: leadexchange.v1.PropertyService.ReindexProperty:output_type -> leadexchange.v1.ReindexPropertyResponse
	11, // 37: leadexchange.v1.PropertyService.MatchPropertiesAdvanced:output_type -> leadexchange.v1.MatchPropertiesResponse
	17, // 38: leadexchange.v1.PropertyService.GetPropertyJSONLD:output_type -> leadexchange.v1.GetPropertyJSONLDResponse
	19, // 39: leadexchange.v1.PropertyService.GenerateListingContent:output_type -> leadexchange.v1.GenerateListingContentResponse
	23, // 40: leadexchange.v1.PropertyService.AnalyzePropertyImages:output_type -> leadexchange.v1.AnalyzePropertyImagesResponse
	31, // [31:41] is the sub-list for method output_type
	21, // [21:31] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_property_proto_init() }
func file_property_proto_init() {
	if File_property_proto != nil {
		return
	}
	file_property_proto_msgTypes[0].OneofWrappers = []any{}
	file_property_proto_msgTypes[1].OneofWrappers = []any{}
	file_property_proto_msgTypes[3].OneofWrappers = []any{}
	file_property_proto_msgTypes[5].OneofWrappers = []any{}
	file_property_proto_msgTypes[7].OneofWrappers = []any{}
	file_property_proto_msgTypes[8].OneofWrappers = []any{}
	file_property_proto_msgTypes[12].OneofWrappers = []any{}
	file_property_proto_msgTypes[13].OneofWrappers = []any{}
	file_property_proto_msgTypes[14].OneofWrappers = []any{}
	file_property_proto_msgTypes[16].OneofWrappers = []any{}
	file_property_proto_msgTypes[20].OneofWrappers = []any{}
	file_property_proto_msgTypes[22].OneofWrappers = []any{}
	file_property_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_property_proto_rawDesc), len(file_property_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_property_proto_goTypes,
		DependencyIndexes: file_property_proto_depIdxs,
		EnumInfos:         file_property_proto_enumTypes,
		MessageInfos:      file_property_proto_msgTypes,
	}.Build()
	File_property_proto = out.File
	file_property_proto_goTypes = nil
	file_property_proto_depIdxs = nil
}
