// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: property.proto

package leadexchangev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _property_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Property with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Property) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Property with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PropertyMultiError, or nil
// if none found.
func (m *Property) ValidateAll() error {
	return m.validate(true)
}

func (m *Property) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PropertyId

	if utf8.RuneCountInString(m.GetTitle()) < 3 {
		err := PropertyValidationError{
			field:  "Title",
			reason: "value length must be at least 3 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Description

	if utf8.RuneCountInString(m.GetAddress()) < 5 {
		err := PropertyValidationError{
			field:  "Address",
			reason: "value length must be at least 5 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for PropertyType

	// no validation rules for Status

	if err := m._validateUuid(m.GetOwnerUserId()); err != nil {
		err = PropertyValidationError{
			field:  "OwnerUserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetCreatedUserId()); err != nil {
		err = PropertyValidationError{
			field:  "CreatedUserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if m.Area != nil {
		// no validation rules for Area
	}

	if m.Price != nil {
		// no validation rules for Price
	}

	if m.Rooms != nil {
		// no validation rules for Rooms
	}

	if m.City != nil {
		// no validation rules for City
	}

	if len(errors) > 0 {
		return PropertyMultiError(errors)
	}

	return nil
}

func (m *Property) _validateUuid(uuid string) error {
	if matched := _property_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PropertyMultiError is an error wrapping multiple validation errors returned
// by Property.ValidateAll() if the designated constraints aren't met.
type PropertyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PropertyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PropertyMultiError) AllErrors() []error { return m }

// PropertyValidationError is the validation error returned by
// Property.Validate if the designated constraints aren't met.
type PropertyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PropertyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PropertyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PropertyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PropertyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PropertyValidationError) ErrorName() string { return "PropertyValidationError" }

// Error satisfies the builtin error interface
func (e PropertyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProperty.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PropertyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PropertyValidationError{}

// Validate checks the field values on CreatePropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreatePropertyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatePropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatePropertyRequestMultiError, or nil if none found.
func (m *CreatePropertyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatePropertyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTitle()) < 3 {
		err := CreatePropertyRequestValidationError{
			field:  "Title",
			reason: "value length must be at least 3 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Description

	if utf8.RuneCountInString(m.GetAddress()) < 5 {
		err := CreatePropertyRequestValidationError{
			field:  "Address",
			reason: "value length must be at least 5 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := PropertyType_name[int32(m.GetPropertyType())]; !ok {
		err := CreatePropertyRequestValidationError{
			field:  "PropertyType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Area != nil {
		// no validation rules for Area
	}

	if m.Price != nil {
		// no validation rules for Price
	}

	if m.Rooms != nil {
		// no validation rules for Rooms
	}

	if m.City != nil {
		// no validation rules for City
	}

	if len(errors) > 0 {
		return CreatePropertyRequestMultiError(errors)
	}

	return nil
}

// CreatePropertyRequestMultiError is an error wrapping multiple validation
// errors returned by CreatePropertyRequest.ValidateAll() if the designated
// constraints aren't met.
type CreatePropertyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatePropertyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatePropertyRequestMultiError) AllErrors() []error { return m }

// CreatePropertyRequestValidationError is the validation error returned by
// CreatePropertyRequest.Validate if the designated constraints aren't met.
type CreatePropertyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePropertyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePropertyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePropertyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePropertyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePropertyRequestValidationError) ErrorName() string {
	return "CreatePropertyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePropertyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePropertyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePropertyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePropertyRequestValidationError{}

// Validate checks the field values on GetPropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPropertyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPropertyRequestMultiError, or nil if none found.
func (m *GetPropertyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPropertyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetPropertyId()); err != nil {
		err = GetPropertyRequestValidationError{
			field:  "PropertyId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetPropertyRequestMultiError(errors)
	}

	return nil
}

func (m *GetPropertyRequest) _validateUuid(uuid string) error {
	if matched := _property_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetPropertyRequestMultiError is an error wrapping multiple validation errors
// returned by GetPropertyRequest.ValidateAll() if the designated constraints
// aren't met.
type GetPropertyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPropertyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPropertyRequestMultiError) AllErrors() []error { return m }

// GetPropertyRequestValidationError is the validation error returned by
// GetPropertyRequest.Validate if the designated constraints aren't met.
type GetPropertyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPropertyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPropertyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPropertyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPropertyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPropertyRequestValidationError) ErrorName() string {
	return "GetPropertyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetPropertyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPropertyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPropertyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPropertyRequestValidationError{}

// Validate checks the field values on ListPropertiesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPropertiesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPropertiesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPropertiesRequestMultiError, or nil if none found.
func (m *ListPropertiesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPropertiesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFilter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListPropertiesRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListPropertiesRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListPropertiesRequestValidationError{
				field:  "Filter",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.PageSize != nil {
		// no validation rules for PageSize
	}

	if m.PageToken != nil {
		// no validation rules for PageToken
	}

	if m.OrderBy != nil {
		// no validation rules for OrderBy
	}

	if m.OrderDirection != nil {
		// no validation rules for OrderDirection
	}

	if len(errors) > 0 {
		return ListPropertiesRequestMultiError(errors)
	}

	return nil
}

// ListPropertiesRequestMultiError is an error wrapping multiple validation
// errors returned by ListPropertiesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListPropertiesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPropertiesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPropertiesRequestMultiError) AllErrors() []error { return m }

// ListPropertiesRequestValidationError is the validation error returned by
// ListPropertiesRequest.Validate if the designated constraints aren't met.
type ListPropertiesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPropertiesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPropertiesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPropertiesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPropertiesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPropertiesRequestValidationError) ErrorName() string {
	return "ListPropertiesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPropertiesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPropertiesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPropertiesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPropertiesRequestValidationError{}

// Validate checks the field values on ListPropertiesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPropertiesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPropertiesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPropertiesResponseMultiError, or nil if none found.
func (m *ListPropertiesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPropertiesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetProperties() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPropertiesResponseValidationError{
						field:  fmt.Sprintf("Properties[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPropertiesResponseValidationError{
						field:  fmt.Sprintf("Properties[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPropertiesResponseValidationError{
					field:  fmt.Sprintf("Properties[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListPropertiesResponseMultiError(errors)
	}

	return nil
}

// ListPropertiesResponseMultiError is an error wrapping multiple validation
// errors returned by ListPropertiesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListPropertiesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPropertiesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPropertiesResponseMultiError) AllErrors() []error { return m }

// ListPropertiesResponseValidationError is the validation error returned by
// ListPropertiesResponse.Validate if the designated constraints aren't met.
type ListPropertiesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPropertiesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPropertiesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPropertiesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPropertiesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPropertiesResponseValidationError) ErrorName() string {
	return "ListPropertiesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPropertiesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPropertiesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPropertiesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPropertiesResponseValidationError{}

// Validate checks the field values on UpdatePropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdatePropertyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdatePropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdatePropertyRequestMultiError, or nil if none found.
func (m *UpdatePropertyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdatePropertyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetPropertyId()); err != nil {
		err = UpdatePropertyRequestValidationError{
			field:  "PropertyId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Title != nil {
		// no validation rules for Title
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if m.Address != nil {
		// no validation rules for Address
	}

	if m.PropertyType != nil {
		// no validation rules for PropertyType
	}

	if m.Area != nil {
		// no validation rules for Area
	}

	if m.Price != nil {
		// no validation rules for Price
	}

	if m.Rooms != nil {
		// no validation rules for Rooms
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.OwnerUserId != nil {
		// no validation rules for OwnerUserId
	}

	if m.City != nil {
		// no validation rules for City
	}

	if len(errors) > 0 {
		return UpdatePropertyRequestMultiError(errors)
	}

	return nil
}

func (m *UpdatePropertyRequest) _validateUuid(uuid string) error {
	if matched := _property_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// UpdatePropertyRequestMultiError is an error wrapping multiple validation
// errors returned by UpdatePropertyRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdatePropertyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdatePropertyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdatePropertyRequestMultiError) AllErrors() []error { return m }

// UpdatePropertyRequestValidationError is the validation error returned by
// UpdatePropertyRequest.Validate if the designated constraints aren't met.
type UpdatePropertyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatePropertyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatePropertyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatePropertyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatePropertyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatePropertyRequestValidationError) ErrorName() string {
	return "UpdatePropertyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdatePropertyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatePropertyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatePropertyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatePropertyRequestValidationError{}

// Validate checks the field values on PropertyResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PropertyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PropertyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PropertyResponseMultiError, or nil if none found.
func (m *PropertyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PropertyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProperty()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PropertyResponseValidationError{
					field:  "Property",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PropertyResponseValidationError{
					field:  "Property",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProperty()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PropertyResponseValidationError{
				field:  "Property",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PropertyResponseMultiError(errors)
	}

	return nil
}

// PropertyResponseMultiError is an error wrapping multiple validation errors
// returned by PropertyResponse.ValidateAll() if the designated constraints
// aren't met.
type PropertyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PropertyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PropertyResponseMultiError) AllErrors() []error { return m }

// PropertyResponseValidationError is the validation error returned by
// PropertyResponse.Validate if the designated constraints aren't met.
type PropertyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PropertyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PropertyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PropertyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PropertyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PropertyResponseValidationError) ErrorName() string { return "PropertyResponseValidationError" }

// Error satisfies the builtin error interface
func (e PropertyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPropertyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PropertyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PropertyResponseValidationError{}

// Validate checks the field values on MatchPropertiesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MatchPropertiesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MatchPropertiesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MatchPropertiesRequestMultiError, or nil if none found.
func (m *MatchPropertiesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MatchPropertiesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetLeadId()); err != nil {
		err = MatchPropertiesRequestValidationError{
			field:  "LeadId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetFilter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MatchPropertiesRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MatchPropertiesRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MatchPropertiesRequestValidationError{
				field:  "Filter",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Limit != nil {
		// no validation rules for Limit
	}

	if len(errors) > 0 {
		return MatchPropertiesRequestMultiError(errors)
	}

	return nil
}

func (m *MatchPropertiesRequest) _validateUuid(uuid string) error {
	if matched := _property_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// MatchPropertiesRequestMultiError is an error wrapping multiple validation
// errors returned by MatchPropertiesRequest.ValidateAll() if the designated
// constraints aren't met.
type MatchPropertiesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MatchPropertiesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MatchPropertiesRequestMultiError) AllErrors() []error { return m }

// MatchPropertiesRequestValidationError is the validation error returned by
// MatchPropertiesRequest.Validate if the designated constraints aren't met.
type MatchPropertiesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MatchPropertiesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MatchPropertiesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MatchPropertiesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MatchPropertiesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MatchPropertiesRequestValidationError) ErrorName() string {
	return "MatchPropertiesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e MatchPropertiesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMatchPropertiesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MatchPropertiesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MatchPropertiesRequestValidationError{}

// Validate checks the field values on MatchedProperty with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *MatchedProperty) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MatchedProperty with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MatchedPropertyMultiError, or nil if none found.
func (m *MatchedProperty) ValidateAll() error {
	return m.validate(true)
}

func (m *MatchedProperty) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProperty()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MatchedPropertyValidationError{
					field:  "Property",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MatchedPropertyValidationError{
					field:  "Property",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProperty()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MatchedPropertyValidationError{
				field:  "Property",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Similarity

	if m.TotalScore != nil {
		// no validation rules for TotalScore
	}

	if m.PriceScore != nil {
		// no validation rules for PriceScore
	}

	if m.DistrictScore != nil {
		// no validation rules for DistrictScore
	}

	if m.RoomsScore != nil {
		// no validation rules for RoomsScore
	}

	if m.AreaScore != nil {
		// no validation rules for AreaScore
	}

	if m.SemanticScore != nil {
		// no validation rules for SemanticScore
	}

	if m.MatchExplanation != nil {
		// no validation rules for MatchExplanation
	}

	if len(errors) > 0 {
		return MatchedPropertyMultiError(errors)
	}

	return nil
}

// MatchedPropertyMultiError is an error wrapping multiple validation errors
// returned by MatchedProperty.ValidateAll() if the designated constraints
// aren't met.
type MatchedPropertyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MatchedPropertyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MatchedPropertyMultiError) AllErrors() []error { return m }

// MatchedPropertyValidationError is the validation error returned by
// MatchedProperty.Validate if the designated constraints aren't met.
type MatchedPropertyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MatchedPropertyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MatchedPropertyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MatchedPropertyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MatchedPropertyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MatchedPropertyValidationError) ErrorName() string { return "MatchedPropertyValidationError" }

// Error satisfies the builtin error interface
func (e MatchedPropertyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMatchedProperty.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MatchedPropertyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MatchedPropertyValidationError{}

// Validate checks the field values on MatchPropertiesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MatchPropertiesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MatchPropertiesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MatchPropertiesResponseMultiError, or nil if none found.
func (m *MatchPropertiesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MatchPropertiesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMatches() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MatchPropertiesResponseValidationError{
						field:  fmt.Sprintf("Matches[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MatchPropertiesResponseValidationError{
						field:  fmt.Sprintf("Matches[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MatchPropertiesResponseValidationError{
					field:  fmt.Sprintf("Matches[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MatchPropertiesResponseMultiError(errors)
	}

	return nil
}

// MatchPropertiesResponseMultiError is an error wrapping multiple validation
// errors returned by MatchPropertiesResponse.ValidateAll() if the designated
// constraints aren't met.
type MatchPropertiesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MatchPropertiesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MatchPropertiesResponseMultiError) AllErrors() []error { return m }

// MatchPropertiesResponseValidationError is the validation error returned by
// MatchPropertiesResponse.Validate if the designated constraints aren't met.
type MatchPropertiesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MatchPropertiesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MatchPropertiesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MatchPropertiesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MatchPropertiesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MatchPropertiesResponseValidationError) ErrorName() string {
	return "MatchPropertiesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MatchPropertiesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMatchPropertiesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MatchPropertiesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MatchPropertiesResponseValidationError{}

// Validate checks the field values on ReindexPropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReindexPropertyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReindexPropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReindexPropertyRequestMultiError, or nil if none found.
func (m *ReindexPropertyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReindexPropertyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetPropertyId()); err != nil {
		err = ReindexPropertyRequestValidationError{
			field:  "PropertyId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ReindexPropertyRequestMultiError(errors)
	}

	return nil
}

func (m *ReindexPropertyRequest) _validateUuid(uuid string) error {
	if matched := _property_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// ReindexPropertyRequestMultiError is an error wrapping multiple validation
// errors returned by ReindexPropertyRequest.ValidateAll() if the designated
// constraints aren't met.
type ReindexPropertyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReindexPropertyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReindexPropertyRequestMultiError) AllErrors() []error { return m }

// ReindexPropertyRequestValidationError is the validation error returned by
// ReindexPropertyRequest.Validate if the designated constraints aren't met.
type ReindexPropertyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReindexPropertyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReindexPropertyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReindexPropertyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReindexPropertyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReindexPropertyRequestValidationError) ErrorName() string {
	return "ReindexPropertyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReindexPropertyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReindexPropertyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReindexPropertyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReindexPropertyRequestValidationError{}

// Validate checks the field values on ReindexPropertyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReindexPropertyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReindexPropertyResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReindexPropertyResponseMultiError, or nil if none found.
func (m *ReindexPropertyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReindexPropertyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return ReindexPropertyResponseMultiError(errors)
	}

	return nil
}

// ReindexPropertyResponseMultiError is an error wrapping multiple validation
// errors returned by ReindexPropertyResponse.ValidateAll() if the designated
// constraints aren't met.
type ReindexPropertyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReindexPropertyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReindexPropertyResponseMultiError) AllErrors() []error { return m }

// ReindexPropertyResponseValidationError is the validation error returned by
// ReindexPropertyResponse.Validate if the designated constraints aren't met.
type ReindexPropertyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReindexPropertyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReindexPropertyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReindexPropertyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReindexPropertyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReindexPropertyResponseValidationError) ErrorName() string {
	return "ReindexPropertyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReindexPropertyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReindexPropertyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReindexPropertyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReindexPropertyResponseValidationError{}

// Validate checks the field values on PropertyFilter with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PropertyFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PropertyFilter with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PropertyFilterMultiError,
// or nil if none found.
func (m *PropertyFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *PropertyFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.City != nil {
		// no validation rules for City
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.PropertyType != nil {
		// no validation rules for PropertyType
	}

	if m.MinPrice != nil {
		// no validation rules for MinPrice
	}

	if m.MaxPrice != nil {
		// no validation rules for MaxPrice
	}

	if m.MinRooms != nil {
		// no validation rules for MinRooms
	}

	if m.MaxRooms != nil {
		// no validation rules for MaxRooms
	}

	if len(errors) > 0 {
		return PropertyFilterMultiError(errors)
	}

	return nil
}

// PropertyFilterMultiError is an error wrapping multiple validation errors
// returned by PropertyFilter.ValidateAll() if the designated constraints
// aren't met.
type PropertyFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PropertyFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PropertyFilterMultiError) AllErrors() []error { return m }

// PropertyFilterValidationError is the validation error returned by
// PropertyFilter.Validate if the designated constraints aren't met.
type PropertyFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PropertyFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PropertyFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PropertyFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PropertyFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PropertyFilterValidationError) ErrorName() string { return "PropertyFilterValidationError" }

// Error satisfies the builtin error interface
func (e PropertyFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPropertyFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PropertyFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PropertyFilterValidationError{}

// Validate checks the field values on MatchPropertiesAdvancedRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MatchPropertiesAdvancedRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MatchPropertiesAdvancedRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// MatchPropertiesAdvancedRequestMultiError, or nil if none found.
func (m *MatchPropertiesAdvancedRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MatchPropertiesAdvancedRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetLeadId()); err != nil {
		err = MatchPropertiesAdvancedRequestValidationError{
			field:  "LeadId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetFilter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MatchPropertiesAdvancedRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MatchPropertiesAdvancedRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MatchPropertiesAdvancedRequestValidationError{
				field:  "Filter",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Limit != nil {
		// no validation rules for Limit
	}

	if m.UseHybridSearch != nil {
		// no validation rules for UseHybridSearch
	}

	if m.UseReranker != nil {
		// no validation rules for UseReranker
	}

	if m.UseDynamicWeights != nil {
		// no validation rules for UseDynamicWeights
	}

	if len(errors) > 0 {
		return MatchPropertiesAdvancedRequestMultiError(errors)
	}

	return nil
}

func (m *MatchPropertiesAdvancedRequest) _validateUuid(uuid string) error {
	if matched := _property_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// MatchPropertiesAdvancedRequestMultiError is an error wrapping multiple
// validation errors returned by MatchPropertiesAdvancedRequest.ValidateAll()
// if the designated constraints aren't met.
type MatchPropertiesAdvancedRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MatchPropertiesAdvancedRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MatchPropertiesAdvancedRequestMultiError) AllErrors() []error { return m }

// MatchPropertiesAdvancedRequestValidationError is the validation error
// returned by MatchPropertiesAdvancedRequest.Validate if the designated
// constraints aren't met.
type MatchPropertiesAdvancedRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MatchPropertiesAdvancedRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MatchPropertiesAdvancedRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MatchPropertiesAdvancedRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MatchPropertiesAdvancedRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MatchPropertiesAdvancedRequestValidationError) ErrorName() string {
	return "MatchPropertiesAdvancedRequestValidationError"
}

// Error satisfies the builtin error interface
func (e MatchPropertiesAdvancedRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMatchPropertiesAdvancedRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MatchPropertiesAdvancedRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MatchPropertiesAdvancedRequestValidationError{}

// Validate checks the field values on GetPropertyJSONLDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPropertyJSONLDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPropertyJSONLDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPropertyJSONLDRequestMultiError, or nil if none found.
func (m *GetPropertyJSONLDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPropertyJSONLDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetPropertyId()); err != nil {
		err = GetPropertyJSONLDRequestValidationError{
			field:  "PropertyId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.BaseUrl != nil {
		// no validation rules for BaseUrl
	}

	if len(errors) > 0 {
		return GetPropertyJSONLDRequestMultiError(errors)
	}

	return nil
}

func (m *GetPropertyJSONLDRequest) _validateUuid(uuid string) error {
	if matched := _property_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetPropertyJSONLDRequestMultiError is an error wrapping multiple validation
// errors returned by GetPropertyJSONLDRequest.ValidateAll() if the designated
// constraints aren't met.
type GetPropertyJSONLDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPropertyJSONLDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPropertyJSONLDRequestMultiError) AllErrors() []error { return m }

// GetPropertyJSONLDRequestValidationError is the validation error returned by
// GetPropertyJSONLDRequest.Validate if the designated constraints aren't met.
type GetPropertyJSONLDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPropertyJSONLDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPropertyJSONLDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPropertyJSONLDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPropertyJSONLDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPropertyJSONLDRequestValidationError) ErrorName() string {
	return "GetPropertyJSONLDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetPropertyJSONLDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPropertyJSONLDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPropertyJSONLDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPropertyJSONLDRequestValidationError{}

// Validate checks the field values on GetPropertyJSONLDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPropertyJSONLDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPropertyJSONLDResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPropertyJSONLDResponseMultiError, or nil if none found.
func (m *GetPropertyJSONLDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPropertyJSONLDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for JsonldData

	if len(errors) > 0 {
		return GetPropertyJSONLDResponseMultiError(errors)
	}

	return nil
}

// GetPropertyJSONLDResponseMultiError is an error wrapping multiple validation
// errors returned by GetPropertyJSONLDResponse.ValidateAll() if the
// designated constraints aren't met.
type GetPropertyJSONLDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPropertyJSONLDResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPropertyJSONLDResponseMultiError) AllErrors() []error { return m }

// GetPropertyJSONLDResponseValidationError is the validation error returned by
// GetPropertyJSONLDResponse.Validate if the designated constraints aren't met.
type GetPropertyJSONLDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPropertyJSONLDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPropertyJSONLDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPropertyJSONLDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPropertyJSONLDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPropertyJSONLDResponseValidationError) ErrorName() string {
	return "GetPropertyJSONLDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPropertyJSONLDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPropertyJSONLDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPropertyJSONLDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPropertyJSONLDResponseValidationError{}

// Validate checks the field values on GenerateListingContentRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateListingContentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateListingContentRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GenerateListingContentRequestMultiError, or nil if none found.
func (m *GenerateListingContentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateListingContentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.PropertyId != nil {
		// no validation rules for PropertyId
	}

	if m.PropertyType != nil {
		// no validation rules for PropertyType
	}

	if m.Address != nil {
		// no validation rules for Address
	}

	if m.City != nil {
		// no validation rules for City
	}

	if m.Price != nil {
		// no validation rules for Price
	}

	if m.Rooms != nil {
		// no validation rules for Rooms
	}

	if m.Area != nil {
		// no validation rules for Area
	}

	if m.ExistingTitle != nil {
		// no validation rules for ExistingTitle
	}

	if m.ExistingDescription != nil {
		// no validation rules for ExistingDescription
	}

	if len(errors) > 0 {
		return GenerateListingContentRequestMultiError(errors)
	}

	return nil
}

// GenerateListingContentRequestMultiError is an error wrapping multiple
// validation errors returned by GenerateListingContentRequest.ValidateAll()
// if the designated constraints aren't met.
type GenerateListingContentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateListingContentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateListingContentRequestMultiError) AllErrors() []error { return m }

// GenerateListingContentRequestValidationError is the validation error
// returned by GenerateListingContentRequest.Validate if the designated
// constraints aren't met.
type GenerateListingContentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateListingContentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateListingContentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateListingContentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateListingContentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateListingContentRequestValidationError) ErrorName() string {
	return "GenerateListingContentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateListingContentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateListingContentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateListingContentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateListingContentRequestValidationError{}

// Validate checks the field values on GenerateListingContentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateListingContentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateListingContentResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GenerateListingContentResponseMultiError, or nil if none found.
func (m *GenerateListingContentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateListingContentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for Confidence

	if len(errors) > 0 {
		return GenerateListingContentResponseMultiError(errors)
	}

	return nil
}

// GenerateListingContentResponseMultiError is an error wrapping multiple
// validation errors returned by GenerateListingContentResponse.ValidateAll()
// if the designated constraints aren't met.
type GenerateListingContentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateListingContentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateListingContentResponseMultiError) AllErrors() []error { return m }

// GenerateListingContentResponseValidationError is the validation error
// returned by GenerateListingContentResponse.Validate if the designated
// constraints aren't met.
type GenerateListingContentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateListingContentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateListingContentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateListingContentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateListingContentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateListingContentResponseValidationError) ErrorName() string {
	return "GenerateListingContentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateListingContentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateListingContentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateListingContentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateListingContentResponseValidationError{}

// Validate checks the field values on AnalyzePropertyImagesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AnalyzePropertyImagesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AnalyzePropertyImagesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AnalyzePropertyImagesRequestMultiError, or nil if none found.
func (m *AnalyzePropertyImagesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AnalyzePropertyImagesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetPropertyId()); err != nil {
		err = AnalyzePropertyImagesRequestValidationError{
			field:  "PropertyId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AnalyzePropertyImagesRequestMultiError(errors)
	}

	return nil
}

func (m *AnalyzePropertyImagesRequest) _validateUuid(uuid string) error {
	if matched := _property_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AnalyzePropertyImagesRequestMultiError is an error wrapping multiple
// validation errors returned by AnalyzePropertyImagesRequest.ValidateAll() if
// the designated constraints aren't met.
type AnalyzePropertyImagesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AnalyzePropertyImagesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AnalyzePropertyImagesRequestMultiError) AllErrors() []error { return m }

// AnalyzePropertyImagesRequestValidationError is the validation error returned
// by AnalyzePropertyImagesRequest.Validate if the designated constraints
// aren't met.
type AnalyzePropertyImagesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AnalyzePropertyImagesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AnalyzePropertyImagesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AnalyzePropertyImagesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AnalyzePropertyImagesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AnalyzePropertyImagesRequestValidationError) ErrorName() string {
	return "AnalyzePropertyImagesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AnalyzePropertyImagesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAnalyzePropertyImagesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AnalyzePropertyImagesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AnalyzePropertyImagesRequestValidationError{}

// Validate checks the field values on ImageFeature with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ImageFeature) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ImageFeature with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ImageFeatureMultiError, or
// nil if none found.
func (m *ImageFeature) ValidateAll() error {
	return m.validate(true)
}

func (m *ImageFeature) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Confidence

	// no validation rules for Category

	if len(errors) > 0 {
		return ImageFeatureMultiError(errors)
	}

	return nil
}

// ImageFeatureMultiError is an error wrapping multiple validation errors
// returned by ImageFeature.ValidateAll() if the designated constraints aren't met.
type ImageFeatureMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ImageFeatureMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ImageFeatureMultiError) AllErrors() []error { return m }

// ImageFeatureValidationError is the validation error returned by
// ImageFeature.Validate if the designated constraints aren't met.
type ImageFeatureValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ImageFeatureValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ImageFeatureValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ImageFeatureValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ImageFeatureValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ImageFeatureValidationError) ErrorName() string { return "ImageFeatureValidationError" }

// Error satisfies the builtin error interface
func (e ImageFeatureValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sImageFeature.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ImageFeatureValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ImageFeatureValidationError{}

// Validate checks the field values on ImageAnalysisResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ImageAnalysisResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ImageAnalysisResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ImageAnalysisResultMultiError, or nil if none found.
func (m *ImageAnalysisResult) ValidateAll() error {
	return m.validate(true)
}

func (m *ImageAnalysisResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetDetectedFeatures() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ImageAnalysisResultValidationError{
						field:  fmt.Sprintf("DetectedFeatures[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ImageAnalysisResultValidationError{
						field:  fmt.Sprintf("DetectedFeatures[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ImageAnalysisResultValidationError{
					field:  fmt.Sprintf("DetectedFeatures[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for QualityScore

	// no validation rules for Brightness

	if m.RoomType != nil {
		// no validation rules for RoomType
	}

	if m.ViewType != nil {
		// no validation rules for ViewType
	}

	if len(errors) > 0 {
		return ImageAnalysisResultMultiError(errors)
	}

	return nil
}

// ImageAnalysisResultMultiError is an error wrapping multiple validation
// errors returned by ImageAnalysisResult.ValidateAll() if the designated
// constraints aren't met.
type ImageAnalysisResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ImageAnalysisResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ImageAnalysisResultMultiError) AllErrors() []error { return m }

// ImageAnalysisResultValidationError is the validation error returned by
// ImageAnalysisResult.Validate if the designated constraints aren't met.
type ImageAnalysisResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ImageAnalysisResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ImageAnalysisResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ImageAnalysisResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ImageAnalysisResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ImageAnalysisResultValidationError) ErrorName() string {
	return "ImageAnalysisResultValidationError"
}

// Error satisfies the builtin error interface
func (e ImageAnalysisResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sImageAnalysisResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ImageAnalysisResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ImageAnalysisResultValidationError{}

// Validate checks the field values on AnalyzePropertyImagesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AnalyzePropertyImagesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AnalyzePropertyImagesResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// AnalyzePropertyImagesResponseMultiError, or nil if none found.
func (m *AnalyzePropertyImagesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AnalyzePropertyImagesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalImages

	// no validation rules for AverageQuality

	for idx, item := range m.GetAllFeatures() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AnalyzePropertyImagesResponseValidationError{
						field:  fmt.Sprintf("AllFeatures[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AnalyzePropertyImagesResponseValidationError{
						field:  fmt.Sprintf("AllFeatures[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AnalyzePropertyImagesResponseValidationError{
					field:  fmt.Sprintf("AllFeatures[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for OverallAssessment

	for idx, item := range m.GetImageResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AnalyzePropertyImagesResponseValidationError{
						field:  fmt.Sprintf("ImageResults[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AnalyzePropertyImagesResponseValidationError{
						field:  fmt.Sprintf("ImageResults[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AnalyzePropertyImagesResponseValidationError{
					field:  fmt.Sprintf("ImageResults[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AnalyzePropertyImagesResponseMultiError(errors)
	}

	return nil
}

// AnalyzePropertyImagesResponseMultiError is an error wrapping multiple
// validation errors returned by AnalyzePropertyImagesResponse.ValidateAll()
// if the designated constraints aren't met.
type AnalyzePropertyImagesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AnalyzePropertyImagesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AnalyzePropertyImagesResponseMultiError) AllErrors() []error { return m }

// AnalyzePropertyImagesResponseValidationError is the validation error
// returned by AnalyzePropertyImagesResponse.Validate if the designated
// constraints aren't met.
type AnalyzePropertyImagesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AnalyzePropertyImagesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AnalyzePropertyImagesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AnalyzePropertyImagesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AnalyzePropertyImagesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AnalyzePropertyImagesResponseValidationError) ErrorName() string {
	return "AnalyzePropertyImagesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AnalyzePropertyImagesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAnalyzePropertyImagesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AnalyzePropertyImagesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AnalyzePropertyImagesResponseValidationError{}

// Validate checks the field values on ListPropertiesRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPropertiesRequest_Filter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPropertiesRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPropertiesRequest_FilterMultiError, or nil if none found.
func (m *ListPropertiesRequest_Filter) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPropertiesRequest_Filter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.OwnerUserId != nil {
		// no validation rules for OwnerUserId
	}

	if m.CreatedUserId != nil {
		// no validation rules for CreatedUserId
	}

	if m.PropertyType != nil {
		// no validation rules for PropertyType
	}

	if m.MinRooms != nil {
		// no validation rules for MinRooms
	}

	if m.MaxRooms != nil {
		// no validation rules for MaxRooms
	}

	if m.MinPrice != nil {
		// no validation rules for MinPrice
	}

	if m.MaxPrice != nil {
		// no validation rules for MaxPrice
	}

	if m.City != nil {
		// no validation rules for City
	}

	if len(errors) > 0 {
		return ListPropertiesRequest_FilterMultiError(errors)
	}

	return nil
}

// ListPropertiesRequest_FilterMultiError is an error wrapping multiple
// validation errors returned by ListPropertiesRequest_Filter.ValidateAll() if
// the designated constraints aren't met.
type ListPropertiesRequest_FilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPropertiesRequest_FilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPropertiesRequest_FilterMultiError) AllErrors() []error { return m }

// ListPropertiesRequest_FilterValidationError is the validation error returned
// by ListPropertiesRequest_Filter.Validate if the designated constraints
// aren't met.
type ListPropertiesRequest_FilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPropertiesRequest_FilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPropertiesRequest_FilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPropertiesRequest_FilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPropertiesRequest_FilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPropertiesRequest_FilterValidationError) ErrorName() string {
	return "ListPropertiesRequest_FilterValidationError"
}

// Error satisfies the builtin error interface
func (e ListPropertiesRequest_FilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPropertiesRequest_Filter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPropertiesRequest_FilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPropertiesRequest_FilterValidationError{}

// Validate checks the field values on MatchPropertiesRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MatchPropertiesRequest_Filter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MatchPropertiesRequest_Filter with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// MatchPropertiesRequest_FilterMultiError, or nil if none found.
func (m *MatchPropertiesRequest_Filter) ValidateAll() error {
	return m.validate(true)
}

func (m *MatchPropertiesRequest_Filter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.PropertyType != nil {
		// no validation rules for PropertyType
	}

	if m.MinRooms != nil {
		// no validation rules for MinRooms
	}

	if m.MaxRooms != nil {
		// no validation rules for MaxRooms
	}

	if m.MinPrice != nil {
		// no validation rules for MinPrice
	}

	if m.MaxPrice != nil {
		// no validation rules for MaxPrice
	}

	if m.City != nil {
		// no validation rules for City
	}

	if len(errors) > 0 {
		return MatchPropertiesRequest_FilterMultiError(errors)
	}

	return nil
}

// MatchPropertiesRequest_FilterMultiError is an error wrapping multiple
// validation errors returned by MatchPropertiesRequest_Filter.ValidateAll()
// if the designated constraints aren't met.
type MatchPropertiesRequest_FilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MatchPropertiesRequest_FilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MatchPropertiesRequest_FilterMultiError) AllErrors() []error { return m }

// MatchPropertiesRequest_FilterValidationError is the validation error
// returned by MatchPropertiesRequest_Filter.Validate if the designated
// constraints aren't met.
type MatchPropertiesRequest_FilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MatchPropertiesRequest_FilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MatchPropertiesRequest_FilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MatchPropertiesRequest_FilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MatchPropertiesRequest_FilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MatchPropertiesRequest_FilterValidationError) ErrorName() string {
	return "MatchPropertiesRequest_FilterValidationError"
}

// Error satisfies the builtin error interface
func (e MatchPropertiesRequest_FilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMatchPropertiesRequest_Filter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MatchPropertiesRequest_FilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MatchPropertiesRequest_FilterValidationError{}
