// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: property.proto

package leadexchangev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PropertyService_CreateProperty_FullMethodName          = "/leadexchange.v1.PropertyService/CreateProperty"
	PropertyService_GetProperty_FullMethodName             = "/leadexchange.v1.PropertyService/GetProperty"
	PropertyService_ListProperties_FullMethodName          = "/leadexchange.v1.PropertyService/ListProperties"
	PropertyService_UpdateProperty_FullMethodName          = "/leadexchange.v1.PropertyService/UpdateProperty"
	PropertyService_MatchProperties_FullMethodName         = "/leadexchange.v1.PropertyService/MatchProperties"
	PropertyService_ReindexProperty_FullMethodName         = "/leadexchange.v1.PropertyService/ReindexProperty"
	PropertyService_MatchPropertiesAdvanced_FullMethodName = "/leadexchange.v1.PropertyService/MatchPropertiesAdvanced"
	PropertyService_GetPropertyJSONLD_FullMethodName       = "/leadexchange.v1.PropertyService/GetPropertyJSONLD"
	PropertyService_GenerateListingContent_FullMethodName  = "/leadexchange.v1.PropertyService/GenerateListingContent"
	PropertyService_AnalyzePropertyImages_FullMethodName   = "/leadexchange.v1.PropertyService/AnalyzePropertyImages"
)

// PropertyServiceClient is the client API for PropertyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PropertyServiceClient interface {
	// Создать новый объект недвижимости.
	CreateProperty(ctx context.Context, in *CreatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	// Получить информацию о конкретном объекте недвижимости.
	GetProperty(ctx context.Context, in *GetPropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	// Получить список объектов недвижимости по фильтру.
	ListProperties(ctx context.Context, in *ListPropertiesRequest, opts ...grpc.CallOption) (*ListPropertiesResponse, error)
	// Обновить объект недвижимости.
	UpdateProperty(ctx context.Context, in *UpdatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	// Найти подходящие объекты недвижимости для лида по векторному сходству.
	MatchProperties(ctx context.Context, in *MatchPropertiesRequest, opts ...grpc.CallOption) (*MatchPropertiesResponse, error)
	// Переиндексировать объект недвижимости вручную.
	ReindexProperty(ctx context.Context, in *ReindexPropertyRequest, opts ...grpc.CallOption) (*ReindexPropertyResponse, error)
	// Расширенный поиск с гибридным поиском и реранкером.
	MatchPropertiesAdvanced(ctx context.Context, in *MatchPropertiesAdvancedRequest, opts ...grpc.CallOption) (*MatchPropertiesResponse, error)
	// Получить JSON-LD разметку объекта недвижимости (schema.org).
	GetPropertyJSONLD(ctx context.Context, in *GetPropertyJSONLDRequest, opts ...grpc.CallOption) (*GetPropertyJSONLDResponse, error)
	// Сгенерировать заголовок и описание с помощью AI.
	GenerateListingContent(ctx context.Context, in *GenerateListingContentRequest, opts ...grpc.CallOption) (*GenerateListingContentResponse, error)
	// Анализ изображений объекта недвижимости.
	AnalyzePropertyImages(ctx context.Context, in *AnalyzePropertyImagesRequest, opts ...grpc.CallOption) (*AnalyzePropertyImagesResponse, error)
}

type propertyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyServiceClient(cc grpc.ClientConnInterface) PropertyServiceClient {
	return &propertyServiceClient{cc}
}

func (c *propertyServiceClient) CreateProperty(ctx context.Context, in *CreatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, PropertyService_CreateProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) GetProperty(ctx context.Context, in *GetPropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, PropertyService_GetProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) ListProperties(ctx context.Context, in *ListPropertiesRequest, opts ...grpc.CallOption) (*ListPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPropertiesResponse)
	err := c.cc.Invoke(ctx, PropertyService_ListProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) UpdateProperty(ctx context.Context, in *UpdatePropertyRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, PropertyService_UpdateProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) MatchProperties(ctx context.Context, in *MatchPropertiesRequest, opts ...grpc.CallOption) (*MatchPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchPropertiesResponse)
	err := c.cc.Invoke(ctx, PropertyService_MatchProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) ReindexProperty(ctx context.Context, in *ReindexPropertyRequest, opts ...grpc.CallOption) (*ReindexPropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReindexPropertyResponse)
	err := c.cc.Invoke(ctx, PropertyService_ReindexProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) MatchPropertiesAdvanced(ctx context.Context, in *MatchPropertiesAdvancedRequest, opts ...grpc.CallOption) (*MatchPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchPropertiesResponse)
	err := c.cc.Invoke(ctx, PropertyService_MatchPropertiesAdvanced_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) GetPropertyJSONLD(ctx context.Context, in *GetPropertyJSONLDRequest, opts ...grpc.CallOption) (*GetPropertyJSONLDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPropertyJSONLDResponse)
	err := c.cc.Invoke(ctx, PropertyService_GetPropertyJSONLD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) GenerateListingContent(ctx context.Context, in *GenerateListingContentRequest, opts ...grpc.CallOption) (*GenerateListingContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateListingContentResponse)
	err := c.cc.Invoke(ctx, PropertyService_GenerateListingContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyServiceClient) AnalyzePropertyImages(ctx context.Context, in *AnalyzePropertyImagesRequest, opts ...grpc.CallOption) (*AnalyzePropertyImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzePropertyImagesResponse)
	err := c.cc.Invoke(ctx, PropertyService_AnalyzePropertyImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyServiceServer is the server API for PropertyService service.
// All implementations must embed UnimplementedPropertyServiceServer
// for forward compatibility.
type PropertyServiceServer interface {
	// Создать новый объект недвижимости.
	CreateProperty(context.Context, *CreatePropertyRequest) (*PropertyResponse, error)
	// Получить информацию о конкретном объекте недвижимости.
	GetProperty(context.Context, *GetPropertyRequest) (*PropertyResponse, error)
	// Получить список объектов недвижимости по фильтру.
	ListProperties(context.Context, *ListPropertiesRequest) (*ListPropertiesResponse, error)
	// Обновить объект недвижимости.
	UpdateProperty(context.Context, *UpdatePropertyRequest) (*PropertyResponse, error)
	// Найти подходящие объекты недвижимости для лида по векторному сходству.
	MatchProperties(context.Context, *MatchPropertiesRequest) (*MatchPropertiesResponse, error)
	// Переиндексировать объект недвижимости вручную.
	ReindexProperty(context.Context, *ReindexPropertyRequest) (*ReindexPropertyResponse, error)
	// Расширенный поиск с гибридным поиском и реранкером.
	MatchPropertiesAdvanced(context.Context, *MatchPropertiesAdvancedRequest) (*MatchPropertiesResponse, error)
	// Получить JSON-LD разметку объекта недвижимости (schema.org).
	GetPropertyJSONLD(context.Context, *GetPropertyJSONLDRequest) (*GetPropertyJSONLDResponse, error)
	// Сгенерировать заголовок и описание с помощью AI.
	GenerateListingContent(context.Context, *GenerateListingContentRequest) (*GenerateListingContentResponse, error)
	// Анализ изображений объекта недвижимости.
	AnalyzePropertyImages(context.Context, *AnalyzePropertyImagesRequest) (*AnalyzePropertyImagesResponse, error)
	mustEmbedUnimplementedPropertyServiceServer()
}

// UnimplementedPropertyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPropertyServiceServer struct{}

func (UnimplementedPropertyServiceServer) CreateProperty(context.Context, *CreatePropertyRequest) (*PropertyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProperty not implemented")
}
func (UnimplementedPropertyServiceServer) GetProperty(context.Context, *GetPropertyRequest) (*PropertyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProperty not implemented")
}
func (UnimplementedPropertyServiceServer) ListProperties(context.Context, *ListPropertiesRequest) (*ListPropertiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProperties not implemented")
}
func (UnimplementedPropertyServiceServer) UpdateProperty(context.Context, *UpdatePropertyRequest) (*PropertyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProperty not implemented")
}
func (UnimplementedPropertyServiceServer) MatchProperties(context.Context, *MatchPropertiesRequest) (*MatchPropertiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchProperties not implemented")
}
func (UnimplementedPropertyServiceServer) ReindexProperty(context.Context, *ReindexPropertyRequest) (*ReindexPropertyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReindexProperty not implemented")
}
func (UnimplementedPropertyServiceServer) MatchPropertiesAdvanced(context.Context, *MatchPropertiesAdvancedRequest) (*MatchPropertiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchPropertiesAdvanced not implemented")
}
func (UnimplementedPropertyServiceServer) GetPropertyJSONLD(context.Context, *GetPropertyJSONLDRequest) (*GetPropertyJSONLDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPropertyJSONLD not implemented")
}
func (UnimplementedPropertyServiceServer) GenerateListingContent(context.Context, *GenerateListingContentRequest) (*GenerateListingContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateListingContent not implemented")
}
func (UnimplementedPropertyServiceServer) AnalyzePropertyImages(context.Context, *AnalyzePropertyImagesRequest) (*AnalyzePropertyImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzePropertyImages not implemented")
}
func (UnimplementedPropertyServiceServer) mustEmbedUnimplementedPropertyServiceServer() {}
func (UnimplementedPropertyServiceServer) testEmbeddedByValue()                         {}

// UnsafePropertyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyServiceServer will
// result in compilation errors.
type UnsafePropertyServiceServer interface {
	mustEmbedUnimplementedPropertyServiceServer()
}

func RegisterPropertyServiceServer(s grpc.ServiceRegistrar, srv PropertyServiceServer) {
	// If the following call panics, it indicates UnimplementedPropertyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PropertyService_ServiceDesc, srv)
}

func _PropertyService_CreateProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).CreateProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_CreateProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).CreateProperty(ctx, req.(*CreatePropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_GetProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).GetProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_GetProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).GetProperty(ctx, req.(*GetPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_ListProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).ListProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_ListProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).ListProperties(ctx, req.(*ListPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_UpdateProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).UpdateProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_UpdateProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).UpdateProperty(ctx, req.(*UpdatePropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_MatchProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).MatchProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_MatchProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).MatchProperties(ctx, req.(*MatchPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_ReindexProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReindexPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).ReindexProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_ReindexProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).ReindexProperty(ctx, req.(*ReindexPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_MatchPropertiesAdvanced_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchPropertiesAdvancedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).MatchPropertiesAdvanced(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_MatchPropertiesAdvanced_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).MatchPropertiesAdvanced(ctx, req.(*MatchPropertiesAdvancedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_GetPropertyJSONLD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropertyJSONLDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).GetPropertyJSONLD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_GetPropertyJSONLD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).GetPropertyJSONLD(ctx, req.(*GetPropertyJSONLDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_GenerateListingContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateListingContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).GenerateListingContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_GenerateListingContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).GenerateListingContent(ctx, req.(*GenerateListingContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropertyService_AnalyzePropertyImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzePropertyImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServiceServer).AnalyzePropertyImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropertyService_AnalyzePropertyImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServiceServer).AnalyzePropertyImages(ctx, req.(*AnalyzePropertyImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PropertyService_ServiceDesc is the grpc.ServiceDesc for PropertyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropertyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leadexchange.v1.PropertyService",
	HandlerType: (*PropertyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProperty",
			Handler:    _PropertyService_CreateProperty_Handler,
		},
		{
			MethodName: "GetProperty",
			Handler:    _PropertyService_GetProperty_Handler,
		},
		{
			MethodName: "ListProperties",
			Handler:    _PropertyService_ListProperties_Handler,
		},
		{
			MethodName: "UpdateProperty",
			Handler:    _PropertyService_UpdateProperty_Handler,
		},
		{
			MethodName: "MatchProperties",
			Handler:    _PropertyService_MatchProperties_Handler,
		},
		{
			MethodName: "ReindexProperty",
			Handler:    _PropertyService_ReindexProperty_Handler,
		},
		{
			MethodName: "MatchPropertiesAdvanced",
			Handler:    _PropertyService_MatchPropertiesAdvanced_Handler,
		},
		{
			MethodName: "GetPropertyJSONLD",
			Handler:    _PropertyService_GetPropertyJSONLD_Handler,
		},
		{
			MethodName: "GenerateListingContent",
			Handler:    _PropertyService_GenerateListingContent_Handler,
		},
		{
			MethodName: "AnalyzePropertyImages",
			Handler:    _PropertyService_AnalyzePropertyImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "property.proto",
}
